---
permalink: concepts/concept_solidfire_concepts_volumes.html 
sidebar: sidebar 
keywords: what is, element, volume, storage volume, persistent volume 
summary: O sistema de storage NetApp SolidFire provisiona o storage usando volumes. Os volumes são dispositivos de bloco acessados pela rede por clientes iSCSI ou Fibre Channel. 
---
= Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O sistema de storage NetApp Element provisiona o storage usando volumes. Os volumes são dispositivos de bloco acessados pela rede por clientes iSCSI ou Fibre Channel.

O storage Element permite criar, exibir, editar, excluir, clonar, fazer backup ou restaurar volumes para contas de usuário. Você também pode gerenciar cada volume em um cluster e adicionar ou remover volumes em grupos de acesso de volume.



== Volumes persistentes

Os volumes persistentes permitem que os dados de configuração do nó de gerenciamento sejam armazenados em um cluster de storage especificado, em vez de localmente com uma VM, para que os dados possam ser preservados em caso de perda ou remoção do nó de gerenciamento. Volumes persistentes são uma configuração de nó de gerenciamento opcional, mas recomendada.

Uma opção para ativar volumes persistentes está incluída nos scripts de instalação e atualização quando link:../mnode/task_mnode_install.html["implantando um novo nó de gerenciamento"]o . Os volumes persistentes são volumes em um cluster de storage baseado em software Element que contém informações de configuração de nó de gerenciamento para a VM do nó de gerenciamento de host que permanecem além da vida útil da VM. Se o nó de gerenciamento for perdido, uma VM de nó de gerenciamento de substituição poderá se reconetar e recuperar dados de configuração da VM perdida.

A funcionalidade de volumes persistentes, se ativada durante a instalação ou atualização, cria automaticamente vários volumes. Esses volumes, como qualquer volume baseado no software Element, podem ser visualizados usando a interface da Web do software Element, o plug-in do NetApp Element para vCenter Server ou a API, dependendo de sua preferência e instalação. Os volumes persistentes devem estar ativos e em execução com uma conexão iSCSI ao nó de gerenciamento para manter os dados de configuração atuais que podem ser usados para recuperação.


NOTE: Volumes persistentes associados a serviços de gerenciamento são criados e atribuídos a uma nova conta durante a instalação ou atualização. Se você estiver usando volumes persistentes, não modifique ou exclua os volumes ou a conta associada
