---
permalink: storage/concept_system_manage_key_get_started_with_external_key_management.html 
sidebar: sidebar 
keywords: kmip, master key, key management, encryption at rest, software encryption at rest, ekm, ak, eks, seds 
summary: 'O gerenciamento de chaves externas (EKM) fornece gerenciamento seguro de chaves de autenticação (AK) em conjunto com um servidor de chaves externo fora do cluster (EKS). Os AKs são utilizados para bloquear e desbloquear unidades de encriptação automática (SEDs) quando a encriptação em repouso está ativada no cluster.' 
---
= Comece a usar o gerenciamento de chaves externas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O gerenciamento de chaves externas (EKM) fornece gerenciamento seguro de chaves de autenticação (AK) em conjunto com um servidor de chaves externas (EKS) fora do cluster. Os AKs são utilizados para bloquear e desbloquear unidades de encriptação automática (SEDs) quando link:../concepts/concept_solidfire_concepts_security.html["criptografia em repouso"] o está ativado no cluster. O EKS fornece geração e armazenamento seguros dos AKs. O cluster utiliza o Key Management Interoperability Protocol (KMIP), um protocolo padrão definido PELA OASIS, para se comunicar com o EKS.

* link:task_system_manage_key_set_up_external_key_management.html["Configurar o gerenciamento externo"]
* link:task_system_manage_rekey_software_ear_master_key.html["Rechavear criptografia de software na chave mestra em repouso"]
* link:concept_system_manage_key_recover_inaccessible_or_invalid_authentication_keys["Recuperar chaves de autenticação inacessíveis ou inválidas"]
* link:concept_system_manage_key_external_key_management_api_commands.html["Comandos externos da API de gerenciamento de chaves"]


[discrete]
== Encontre mais informações

* link:../api/reference_element_api_createcluster.html["CreateCluster API que pode ser usada para habilitar a criptografia de software em repouso"]
* https://docs.netapp.com/us-en/element-software/index.html["Documentação do software SolidFire e Element"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentação para versões anteriores dos produtos NetApp SolidFire e Element"^]

