---
permalink: storage/concept_system_manage_solidfire_storage_cluster_administrator_account_types.html 
sidebar: sidebar 
keywords: user types, account, cluster, access active nodes, per-node UI 
summary: 'Existem dois tipos de contas de administrador que podem existir em um cluster de storage que executa o software NetApp Element: A conta de administrador de cluster principal e uma conta de administrador de cluster.' 
---
= Tipos de conta de administrador de cluster de storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Existem dois tipos de contas de administrador que podem existir em um cluster de storage que executa o software NetApp Element: A conta de administrador de cluster principal e uma conta de administrador de cluster.

* * Conta de administrador de cluster principal*
+
Esta conta de administrador é criada quando o cluster é criado. Esta conta é a conta administrativa primária com o mais alto nível de acesso ao cluster. Essa conta é análoga a um usuário root em um sistema Linux. Pode alterar a palavra-passe desta conta de administrador.

* *Conta de administrador de cluster*
+
Você pode dar a uma conta de administrador de cluster um intervalo limitado de acesso administrativo para executar tarefas específicas dentro de um cluster. As credenciais atribuídas a cada conta de administrador de cluster são usadas para autenticar solicitações de API e IU de elementos no sistema de storage.




NOTE: É necessária uma conta de administrador de cluster local (não LDAP) para aceder a nós ativos num cluster através da IU por nó. As credenciais da conta não são necessárias para acessar um nó que ainda não faz parte de um cluster.
