---
permalink: storage/concept_data_manage_data_management.html 
sidebar: sidebar 
keywords: virtual volumes, volumes, manage 
summary: 'Você pode gerenciar os dados em um cluster executando o software Element na guia Gerenciamento na IU do Element. As funções de gerenciamento de cluster disponíveis incluem a criação e gerenciamento de volumes de dados, contas de usuários, grupos de acesso a volume, iniciadores e políticas de qualidade do serviço (QoS).' 
---
= Aprenda sobre como gerenciar volumes e volumes virtuais.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode gerenciar os dados em um cluster executando o software Element na guia Gerenciamento na IU do Element. As funções de gerenciamento de cluster disponíveis incluem a criação e o gerenciamento de volumes de dados, grupos de acesso a volumes, iniciadores e políticas de qualidade do serviço (QoS).



== Trabalhe com volumes

O sistema SolidFire provisiona o storage usando volumes. Os volumes são dispositivos de bloco acessados pela rede por clientes iSCSI ou Fibre Channel. Na página volumes na guia Gerenciamento, você pode criar, modificar, clonar e excluir volumes em um nó. Você também pode exibir estatísticas sobre largura de banda de volume e uso de e/S.

link:../storage/concept_data_manage_volumes_quality_of_service_policies.html["Aprenda a trabalhar com volumes"]



== Trabalhe com volumes virtuais

Você pode exibir informações e executar tarefas para volumes virtuais e seus contentores de storage associados, pontos de extremidade de protocolo, ligações e hosts usando a IU do Element.

O sistema de storage do software NetApp Element é fornecido com o recurso volumes virtuais (vols) desativado. Você deve executar uma tarefa única de habilitar manualmente a funcionalidade do vSphere VVol por meio da IU do Element.

Depois de ativar a funcionalidade VVol, aparece uma guia VVols na interface do usuário que oferece monitoramento relacionado ao VVols e opções de gerenciamento limitadas. Além disso, um componente de software do lado do storage conhecido como Provedor VASA atua como um serviço de reconhecimento de armazenamento para o vSphere. A maioria dos comandos VVols, como criação, clonagem e edição do VVol, são iniciados por um host vCenter Server ou ESXi e traduzidos pelo provedor VASA para APIs do Element para o sistema de storage do software Element. Comandos para criar, excluir e gerenciar contentores de armazenamento e excluir volumes virtuais podem ser iniciados usando a IU do Element.

A maioria das configurações necessárias para o uso dos recursos do Virtual volumes com os sistemas de storage do software Element é feita no vSphere. Consulte o _Guia de configuração do VMware vSphere Virtual volumes for SolidFire Storage_ para Registrar o provedor VASA no vCenter, criar e gerenciar datastores VVol e gerenciar o storage com base em políticas.


NOTE: Para o Element 12,5 e anterior, não Registre mais de um provedor NetApp Element VASA em uma única instância do vCenter. Quando um segundo provedor NetApp Element VASA é adicionado, isso torna todos os armazenamentos de dados VVOL inacessíveis.


NOTE: O suporte DO VASA para vários vCenters está disponível como um patch de atualização se você já registrou um provedor VASA no vCenter. Para instalar, baixe o arquivo VASA39 .tar.gz do https://mysupport.netapp.com/products/element_software/VASA39/index.html["Transferências de software da NetApp"] site e siga as instruções no manifesto. O fornecedor NetApp Element VASA utiliza um certificado NetApp. Com esse patch, o certificado é usado não modificado pelo vCenter para oferecer suporte a vários vCenters para uso em VASA e VVols. Não modifique o certificado. Certificados SSL personalizados não são suportados pela VASA.

link:../storage/task_data_manage_vvol_enable_virtual_volumes.html["Aprenda a trabalhar com volumes virtuais."]



== Trabalhar com grupos de acesso de volume e iniciadores

Pode utilizar iniciadores iSCSI ou iniciadores Fibre Channel para aceder aos volumes definidos nos grupos de acesso de volume.

É possível criar grupos de acesso mapeando IQNs do iniciador iSCSI ou WWPNs Fibre Channel em uma coleção de volumes. Cada IQN que você adicionar a um grupo de acesso pode acessar cada volume no grupo sem exigir autenticação CHAP.

Existem dois tipos de métodos de autenticação CHAP:

* Autenticação CHAP em nível de conta: Você pode atribuir autenticação CHAP para a conta.
* Autenticação CHAP no nível do iniciador: Você pode atribuir um alvo CHAP exclusivo e segredos para iniciadores específicos sem estar vinculado a um único CHAP em uma única conta. Esta autenticação CHAP no nível do iniciador substitui credenciais no nível da conta.


Opcionalmente, com o CHAP por iniciador, você pode aplicar a autorização do iniciador e a autenticação CHAP por iniciador. Essas opções podem ser definidas por iniciador e um grupo de acesso pode conter uma combinação de iniciadores com diferentes opções.

Cada WWPN que você adicionar a um grupo de acesso permite o acesso à rede Fibre Channel aos volumes no grupo de acesso.


NOTE: Os grupos de acesso ao volume têm os seguintes limites:

* Um máximo de 64 IQNs ou WWPNs são permitidos em um grupo de acesso.
* Um grupo de acesso pode ser composto por um máximo de 2000 volumes.
* Um IQN ou WWPN só pode pertencer a um grupo de acesso.
* Um único volume pode pertencer a um máximo de quatro grupos de acesso.


link:../storage/task_data_manage_vol_access_group_create_a_volume_access_group.html["Saiba mais sobre como trabalhar com grupos e iniciadores de acesso em volume."]



== Para mais informações

* https://docs.netapp.com/us-en/element-software/index.html["Documentação do software SolidFire e Element"]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in do NetApp Element para vCenter Server"^]

