---
permalink: storage/concept_intro_drives.html 
sidebar: sidebar 
keywords: drives, physical drives, cluster data, storage node, volume metadata, block drives, clusters 
summary: Um nó de armazenamento contém uma ou mais unidades físicas que são usadas para armazenar uma parte dos dados do cluster. O cluster utiliza a capacidade e o desempenho da unidade após a unidade ter sido adicionada com sucesso a um cluster. 
---
= Unidades
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um nó de armazenamento contém uma ou mais unidades físicas que são usadas para armazenar uma parte dos dados do cluster. O cluster utiliza a capacidade e o desempenho da unidade após a unidade ter sido adicionada com sucesso a um cluster.

Um nó de armazenamento contém dois tipos de unidades:

* *Unidades de metadados de volume*
+
Essas unidades armazenam informações compactadas que definem cada volume, clone ou snapshot em um cluster. A capacidade total da unidade de metadados no sistema determina a quantidade máxima de storage que pode ser provisionada como volumes. A quantidade máxima de storage que pode ser provisionada é independente da quantidade de dados realmente armazenados nas unidades de bloco do cluster. As unidades de metadados de volume armazenam dados de forma redundante em um cluster usando a proteção de dados Double Helix.

+

NOTE: Alguns registos de eventos do sistema e mensagens de erro referem-se a unidades de metadados de volume como unidades de corte.

* * Blocos de unidades*
+
Essas unidades armazenam os blocos de dados compatados e desduplicados para volumes de aplicativos de servidor. Unidades de bloco compõem a maior parte da capacidade de armazenamento do sistema. A maioria das solicitações de leitura de dados já armazenadas no cluster do SolidFire, bem como solicitações para gravação de dados, ocorrem nas unidades de bloco. A capacidade total da unidade de bloco no sistema determina a quantidade máxima de dados que podem ser armazenados, levando em consideração os efeitos da compactação, thin Provisioning e deduplicação.


