---
permalink: storage/task_snapmirror_perform_failback_when_source_volume_exists.html 
sidebar: sidebar 
keywords: element, ui, failback, perform, source volume, snapmirror 
summary: Você pode ressincronizar o volume de origem original e fazer o failover usando a IU do NetApp Element. Este procedimento aplica-se a cenários em que o volume de origem original ainda existe. 
---
= Execute um failback quando o volume de origem ainda existir
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode ressincronizar o volume de origem original e fazer o failover usando a IU do NetApp Element. Este procedimento aplica-se a cenários em que o volume de origem original ainda existe.

. Na IU do elemento, encontre a relação que você quebrou para executar o failover.
. Clique no ícone ações e clique em *Reverse Resync*.
. Confirme a ação.
+

NOTE: A operação Reverse Resync cria uma nova relação na qual as funções dos volumes de origem e destino originais são revertidas (isso resulta em duas relações à medida que a relação original persiste). Todos os novos dados do volume de destino original são transferidos para o volume de origem original como parte da operação de ressincronização reversa. Você pode continuar acessando e gravando dados no volume ativo no lado do destino, mas precisará desconetar todos os hosts do volume de origem e executar uma atualização do SnapMirror antes de redirecionar para o primário original.

. Clique no ícone ações do relacionamento inverso que você acabou de criar e clique em *Atualizar*.
+
Agora que você concluiu a ressincronização reversa e garantiu que não há sessões ativas conetadas ao volume no lado do destino e que os dados mais recentes estejam no volume principal original, você pode executar as seguintes etapas para concluir o failback e reativar o volume primário original:

. Clique no ícone ações da relação inversa e clique em *Break*.
. Clique no ícone ações do relacionamento original e clique em *Resync*.
+

NOTE: O volume primário original agora pode ser montado para retomar as cargas de trabalho de produção no volume primário original. A replicação original do SnapMirror é retomada com base na política e na programação configurada para a relação.

. Depois de confirmar que o status do relacionamento original é "snapmirror", clique no ícone ações do relacionamento inverso e clique em *Delete*.




== Encontre mais informações

xref:concept_snapmirror_failback_scenarios.adoc[Cenários de failback do SnapMirror]
