---
permalink: storage/task_data_manage_vol_access_group_add_multiple_initiators.html 
sidebar: sidebar 
keywords: initiator, add to volume access group, access groups, add multiple initiators, create initiator 
summary: Você pode adicionar vários iniciadores a um grupo de acesso de volume existente para permitir o acesso a volumes no grupo de acesso de volume com ou sem exigir autenticação CHAP. 
---
= Adicione vários iniciadores a um grupo de acesso de volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode adicionar vários iniciadores a um grupo de acesso de volume existente para permitir o acesso a volumes no grupo de acesso de volume com ou sem exigir autenticação CHAP.

Quando você adiciona iniciadores a um grupo de acesso de volume, os iniciadores têm acesso a todos os volumes nesse grupo de acesso de volume.


TIP: Você pode encontrar o iniciador para cada volume clicando no ícone ações e em *Exibir detalhes* para o volume na lista volumes ativos.

Você pode adicionar vários iniciadores a um grupo de acesso de volume existente para habilitar o acesso a volumes e atribuir credenciais CHAP exclusivas para cada iniciador dentro desse grupo de acesso de volume. Isso permite que você aplique essa opção para grupos de acesso de volume que já existem.

Você pode atribuir atributos CHAP baseados em initator usando uma chamada de API. Para adicionar um nome de conta CHAP e credenciais por iniciador, você deve usar a chamada API ModifyInitiator para remover e adicionar acesso e atributos CHAP.

Para obter detalhes, link:../api/index.html["Gerencie o storage com a API Element"]consulte .

.Passos
. Clique em *Management* > *Initiators*.
. Selecione os iniciadores que pretende adicionar a um grupo de acesso.
. Clique no botão *ações em massa*.
. Clique em *Add to volume Access Group*.
. Na caixa de diálogo Adicionar ao Grupo de Acesso por volume, selecione um grupo de acesso na lista *Grupo de Acesso por volume*.
. Clique em *Add*.

