---
permalink: storage/task_system_manage_cluster_ntp_configure.html 
sidebar: sidebar 
keywords: ntp, cluster, query, fqdn, dns server 
summary: 'Você pode instruir cada nó em um cluster a consultar um servidor NTP (Network Time Protocol) para obter atualizações. O cluster contacta apenas servidores configurados e solicita informações NTP a partir deles.' 
---
= Configurar servidores Network Time Protocol para o cluster a consultar
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode instruir cada nó em um cluster a consultar um servidor NTP (Network Time Protocol) para obter atualizações. O cluster contacta apenas servidores configurados e solicita informações NTP a partir deles.

Configure o NTP no cluster para apontar para um servidor NTP local. Você pode usar o endereço IP ou o nome do host FQDN. O servidor NTP predefinido no momento da criação do cluster é definido como us.pool.ntp.org; no entanto, uma ligação a este site nem sempre pode ser feita dependendo da localização física do cluster SolidFire.

O uso do FQDN depende se as configurações de DNS do nó de armazenamento individual estão implementadas e operacionais. Para fazer isso, configure os servidores DNS em cada nó de armazenamento e certifique-se de que as portas estão abertas, revisando a página requisitos de porta de rede.

Pode introduzir até cinco servidores NTP diferentes.


NOTE: Você pode usar endereços IPv4 e IPv6.

.O que você vai precisar
Você deve ter o administrador de cluster Privileges para configurar essa configuração.

.Passos
. Configure uma lista de IPs e/ou FQDNs nas configurações do servidor.
. Certifique-se de que o DNS está configurado corretamente nos nós.
. Clique em *Cluster* > *Settings*.
. Em Network Time Protocol Settings (Definições do protocolo de tempo de rede), selecione *no*, que utiliza a configuração NTP padrão.
. Clique em *Salvar alterações*.




== Encontre mais informações

* https://docs.netapp.com/us-en/element-software/index.html["Documentação do software SolidFire e Element"]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in do NetApp Element para vCenter Server"^]

