---
permalink: storage/task_post_deploy_credential_change_ipmi_password.html 
sidebar: sidebar 
keywords: ipmi, password, intelligent platform management interface, netapp, element, h410s, h610s 
summary: 'Você pode alterar a senha de administrador IPMI (Intelligent Platform Management Interface) padrão assim que tiver acesso IPMI remoto ao nó. Você pode querer fazer isso se houver atualizações de instalação.' 
---
= Altere a senha padrão do IPMI para nós
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode alterar a senha de administrador IPMI (Intelligent Platform Management Interface) padrão assim que tiver acesso IPMI remoto ao nó. Você pode querer fazer isso se houver atualizações de instalação.

Para obter detalhes sobre como configurar o acesso IPM para nós, link:https://docs.netapp.com/us-en/hci/docs/hci_prereqs_final_prep.html["Configure o IPMI para cada nó"^]consulte .

Você pode alterar a senha do IPM para esses nós:

* H410S nós
* H610S nós




== Altere a senha padrão do IPMI para H410S nós

Você deve alterar a senha padrão para a conta de administrador IPMI em cada nó de armazenamento assim que configurar a porta de rede IPMI.

.O que você vai precisar
Você deve ter configurado o endereço IP IPMI para cada nó de armazenamento.

.Passos
. Abra um navegador da Web em um computador que possa acessar a rede IPMI e navegue até o endereço IP IPMI do nó.
. Introduza o nome de utilizador `ADMIN` e a palavra-passe `ADMIN` no aviso de início de sessão.
. Ao iniciar sessão, clique no separador *Configuration* (Configuração).
. Clique em *usuários*.
. Selecione o `ADMIN` usuário e clique em *Modificar usuário*.
. Marque a caixa de seleção *alterar senha*.
. Introduza uma nova palavra-passe nos campos *Password* (Palavra-passe) e *Confirm Password* (confirmar palavra-passe).
. Clique em *Modificar* e, em seguida, clique em *OK*.
. Repita este procedimento para quaisquer outros nós H410S com senhas IPMI padrão.




== Altere a senha padrão do IPMI para H610S nós

Você deve alterar a senha padrão para a conta de administrador IPMI em cada nó de armazenamento assim que configurar a porta de rede IPMI.

.O que você vai precisar
Você deve ter configurado o endereço IP IPMI para cada nó de armazenamento.

.Passos
. Abra um navegador da Web em um computador que possa acessar a rede IPMI e navegue até o endereço IP IPMI do nó.
. Introduza o nome de utilizador `root` e a palavra-passe `calvin` no aviso de início de sessão.
. Ao iniciar sessão, clique no ícone de navegação do menu no canto superior esquerdo da página para abrir a gaveta da barra lateral.
. Clique em *Configurações*.
. Clique em *User Management*.
. Selecione o usuário *Administrator* na lista.
. Ative a caixa de verificação *alterar palavra-passe*.
. Insira uma nova senha forte nos campos *Senha* e *confirmar senha*.
. Clique em *Salvar* na parte inferior da página.
. Repita este procedimento para quaisquer outros nós H610S com senhas IPMI padrão.




== Encontre mais informações

* https://docs.netapp.com/us-en/element-software/index.html["Documentação do software SolidFire e Element"]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in do NetApp Element para vCenter Server"^]

