---
permalink: storage/task_data_protection_back_up_volume_to_solidfire.html 
sidebar: sidebar 
keywords: volume backup, solidfire storage cluster 
summary: É possível fazer backup de volumes que residem em um cluster remoto para clusters de storage que executam o software Element. 
---
= Fazer backup de um volume em um cluster de storage SolidFire
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
É possível fazer backup de volumes que residem em um cluster remoto para clusters de storage que executam o software Element.

Certifique-se de que os clusters de origem e destino estejam emparelhados.

link:task_replication_pair_clusters.html["Emparelhe clusters para replicação"]Consulte .

Ao fazer backup ou restaurar de um cluster para outro, o sistema gera uma chave para ser usada como autenticação entre os clusters. Essa chave de gravação de volume em massa permite que o cluster de origem se autentique com o cluster de destino, fornecendo um nível de segurança ao gravar no volume de destino. Como parte do processo de backup ou restauração, você precisa gerar uma chave de gravação de volume em massa a partir do volume de destino antes de iniciar a operação.

. No cluster de destino, *Management* > *volumes*.
. Clique no ícone ações do volume de destino.
. No menu resultante, clique em *Restaurar de*.
. Na caixa de diálogo *Restauração integrada*, em *Restaurar de*, selecione *SolidFire*.
. Selecione uma opção em *Data Format*:
+
** * Nativo*: Um formato compactado legível apenas pelos sistemas de armazenamento SolidFire.
** *Uncompressed*: Um formato não comprimido compatível com outros sistemas.


. Clique em *Generate Key*.
. Copie a chave da caixa *Bulk volume Write Key* para a área de transferência.
. No cluster de origem, vá para *Management* > *volumes*.
. Clique no ícone ações do volume a ser feito backup.
. No menu resultante, clique em *Backup to*.
. Na caixa de diálogo *Backup integrado* em *Backup to*, selecione *SolidFire*.
. Selecione a mesma opção selecionada anteriormente no campo *Data Format*.
. Introduza o endereço IP virtual de gestão do cluster do volume de destino no campo *Remote Cluster MVIP*.
. Introduza o nome de utilizador do cluster remoto no campo *Nome de utilizador do cluster remoto*.
. Introduza a palavra-passe do cluster remoto no campo *Palavra-passe do cluster remoto*.
. No campo *Bulk volume Write Key* (chave de gravação de volume em massa), cole a chave que você gerou no cluster de destino anteriormente.
. Clique em *Iniciar leitura*.

