---
permalink: storage/task_system_manage_fips_create_a_cluster_supporting_fips_drives.html 
sidebar: sidebar 
keywords: fips, security, federal information processing standards, 140-2, cluster, create 
summary: 'A segurança está se tornando cada vez mais crítica para a implantação de soluções em muitos ambientes de clientes. Os padrões federais de processamento de informações (FIPS) são padrões para segurança e interoperabilidade de computadores. A criptografia com certificação FIPS 140-2 para dados em repouso é um componente da solução de segurança geral.' 
---
= Preparar cluster Element para unidades FIPS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A segurança está se tornando cada vez mais crítica para a implantação de soluções em muitos ambientes de clientes. Os Federal Information Processing Standards (FIPS) são padrões para segurança e interoperabilidade de computadores. A criptografia com certificação FIPS 140-2 para dados em repouso é um componente da solução de segurança geral.

Para se preparar para ativar o recurso unidades FIPS, evite misturar nós onde alguns são capazes de unidades FIPS e outros não.

Um cluster é considerado compatível com unidades FIPS com base nas seguintes condições:

* Todas as unidades são certificadas como unidades FIPS.
* Todos os nós são nós de unidades FIPS.
* A encriptação em repouso (EAR) está ativada.
* O recurso unidades FIPS está ativado. Todas as unidades e nós devem ser capazes de FIPS e a criptografia em repouso deve estar habilitada para habilitar o recurso de unidade FIPS.

