---
permalink: storage/task-element-replication-update-replication-relationship-manually.html 
sidebar: sidebar 
keywords: update, replication, relationship, manually 
summary: Talvez seja necessário atualizar manualmente uma relação de replicação se uma atualização falhar devido a um erro de rede. 
---
= Atualizar uma relação de replicação manualmente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Talvez seja necessário atualizar manualmente uma relação de replicação se uma atualização falhar devido a um erro de rede.

.Sobre esta tarefa
Você deve especificar o caminho de origem do elemento no formulário `<hostip:>/lun/<name>`, onde "'lun'" é a cadeia de carateres real "'lun'" e `name` é o nome do volume do elemento.

.Passos
. Atualizar manualmente uma relação de replicação:
+
`snapmirror update -source-path <hostip:>/lun/<name> -destination-path <SVM:volume>|<cluster://SVM/volume>`

+
Para obter a sintaxe completa do comando, consulte a página man.

+
[NOTE]
====
O comando falhará se uma cópia Snapshot comum não existir na origem e no destino.  `snapmirror initialize`Use para reinicializar o relacionamento.

====
+
O exemplo a seguir atualiza a relação entre o volume de origem `0005` no endereço IP 10.0.0.11 e o volume de `volA_dst` destino no `svm_backup`:

+
[listing]
----
cluster_src::> snapmirror update -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst
----

