---
permalink: storage/task_system_manage_virtual_add_a_virtual_network.html 
sidebar: sidebar 
keywords: virtual network, add, cluster configuration, cluster nodes, svip, vlans, vrf, view, network details, 
summary: Você pode adicionar uma nova rede virtual a uma configuração de cluster para habilitar uma conexão de ambiente de alocação a vários clientes a um cluster executando o software Element. 
---
= Adicione uma rede virtual
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode adicionar uma nova rede virtual a uma configuração de cluster para habilitar uma conexão de ambiente de alocação a vários clientes a um cluster executando o software Element.

.O que você vai precisar
* Identifique o bloco de endereços IP que serão atribuídos às redes virtuais nos nós do cluster.
* Identificar um endereço de IP de rede de armazenamento (SVIP) que será usado como um ponto de extremidade para todo o tráfego de armazenamento NetApp Element.



IMPORTANT: Você deve considerar os seguintes critérios para esta configuração:

* As VLANs que não são compatíveis com VRF exigem que os iniciadores estejam na mesma sub-rede que o SVIP.
* As VLANs habilitadas para VRF não exigem que os iniciadores estejam na mesma sub-rede que o SVIP, e o roteamento é suportado.
* O SVIP padrão não requer que os iniciadores estejam na mesma sub-rede que o SVIP, e o roteamento é suportado.


Quando uma rede virtual é adicionada, uma interface para cada nó é criada e cada um requer um endereço IP de rede virtual. O número de endereços IP especificados ao criar uma nova rede virtual deve ser igual ou maior que o número de nós no cluster. Os endereços de rede virtual são provisionados em massa e atribuídos automaticamente a nós individuais. Não é necessário atribuir manualmente endereços de rede virtuais aos nós do cluster.

.Passos
. Clique em *Cluster* > *Network*.
. Clique em *Create VLAN*.
. Na caixa de diálogo *Create a New VLAN* (criar uma nova VLAN), insira valores nos seguintes campos:
+
** *Nome VLAN*
** * VLAN Tag*
** *SVIP*
** *Máscara de rede*
** (Opcional) *Descrição*


. Introduza o endereço *IP inicial* para o intervalo de endereços IP em *blocos de endereços IP*.
. Introduza o *size* do intervalo IP como o número de endereços IP a incluir no bloco.
. Clique em *Adicionar um bloco* para adicionar um bloco não contínuo de endereços IP para esta VLAN.
. Clique em *Create VLAN*.




== Ver detalhes da rede virtual

.Passos
. Clique em *Cluster* > *Network*.
. Reveja os detalhes.
+
** *ID*: ID exclusiva da rede VLAN, que é atribuída pelo sistema.
** *Nome*: Nome exclusivo atribuído pelo usuário para a rede VLAN.
** *VLAN Tag*: Tag VLAN atribuída quando a rede virtual foi criada.
** *SVIP*: Endereço IP virtual de armazenamento atribuído à rede virtual.
** *Máscara de rede*: Máscara de rede para esta rede virtual.
** *Gateway*: Endereço IP exclusivo de um gateway de rede virtual. A VRF deve estar ativada.
** *VRF habilitado*: Indicação de se o roteamento virtual e o encaminhamento estão ativados ou não.
** *IPs usados*: O intervalo de endereços IP de rede virtual usados para a rede virtual.



