---
permalink: storage/task_data_manage_vol_access_group_remove_initiators_from_an_access_group.html 
sidebar: sidebar 
keywords: initiator, remove from volume access group, access groups, remove initiator 
summary: Quando você remove um iniciador de um grupo de acesso, ele não pode mais acessar os volumes nesse grupo de acesso de volume. O acesso normal à conta ao volume não é interrompido. 
---
= Remover iniciadores de um grupo de acesso
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando você remove um iniciador de um grupo de acesso, ele não pode mais acessar os volumes nesse grupo de acesso de volume. O acesso normal à conta ao volume não é interrompido.

Modificar as configurações CHAP em uma conta ou remover iniciadores ou volumes de um grupo de acesso pode fazer com que os iniciadores percam o acesso aos volumes inesperadamente. Para verificar se o acesso ao volume não será perdido inesperadamente, saia sempre das sessões iSCSI que serão afetadas por uma alteração de conta ou grupo de acesso e verifique se os iniciadores podem se reconetar aos volumes depois que quaisquer alterações nas configurações do iniciador e nas configurações do cluster tiverem sido concluídas.

.Passos
. Clique em *Gerenciamento* > *grupos de acesso*.
. Clique no ícone *ações* do grupo de acesso que deseja remover.
. No menu resultante, selecione *Editar*.
. Em Adicionar iniciadores na caixa de diálogo *Editar Grupo de Acesso por volume*, clique na seta na lista *iniciadores*.
. Selecione o ícone x para cada iniciador que deseja remover do grupo de acesso.
. Clique em *Salvar alterações*.

