---
permalink: storage/task-element-replication-enable-snapmirror-cluster.html 
sidebar: sidebar 
keywords: ontap, cli, enable, snapmirror, element, cluster 
summary: É necessário habilitar o SnapMirror no cluster do Element antes de criar uma relação de replicação. Você só pode executar essa tarefa na IU da Web do software Element ou usando os métodos de API. 
---
= Habilite o SnapMirror no cluster do Element
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
É necessário habilitar o SnapMirror no cluster do Element antes de criar uma relação de replicação. Você só pode executar essa tarefa na IU da Web do software Element ou usando o link:../api/reference_element_api_enablefeature.html["Método API"].

.Antes de começar
* O cluster do Element deve estar executando o software NetApp Element versão 10,1 ou posterior.
* O SnapMirror só pode ser habilitado para clusters de elemento usados com volumes NetApp ONTAP.


.Sobre esta tarefa
O sistema Element vem com SnapMirror desativado por padrão. O SnapMirror não é ativado automaticamente como parte de uma nova instalação ou atualização.

[NOTE]
====
Uma vez ativado, o SnapMirror não pode ser desativado. Só pode desativar a funcionalidade SnapMirror e restaurar as predefinições devolvendo o cluster à imagem de fábrica.

====
.Passos
. Clique em *clusters* > *Configurações*.
. Encontre as configurações específicas do cluster para o SnapMirror.
. Clique em *Ativar SnapMirror*.

