---
permalink: api/concept_element_api_drive_api_methods.html 
sidebar: sidebar 
keywords: drive,API,methods,method 
summary: Você pode usar os métodos de API de unidade para adicionar e gerenciar unidades que estão disponíveis para um cluster de armazenamento. Quando você adiciona um nó de armazenamento ao cluster de armazenamento ou instala novas unidades em um nó de armazenamento existente, as unidades estão disponíveis para serem adicionadas ao cluster de armazenamento. 
---
= Métodos da API da unidade
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar os métodos de API de unidade para adicionar e gerenciar unidades que estão disponíveis para um cluster de armazenamento. Quando você adiciona um nó de armazenamento ao cluster de armazenamento ou instala novas unidades em um nó de armazenamento existente, as unidades estão disponíveis para serem adicionadas ao cluster de armazenamento.

* xref:reference_element_api_adddrives.adoc[AddDrives]
* xref:reference_element_api_getdrivehardwareinfo.adoc[GetDriveHardwareInfo]
* xref:reference_element_api_getdrivestats.adoc[GetDriveStats]
* xref:reference_element_api_listdrives.adoc[ListDrives]
* xref:reference_element_api_listdrivestats.adoc[ListDriveStats]
* xref:reference_element_api_removedrives.adoc[RemoveDrives]
* xref:reference_element_api_secureerasedrives.adoc[SecureEraseDrives]




== Encontre mais informações

* https://docs.netapp.com/us-en/element-software/index.html["Documentação do software SolidFire e Element"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentação para versões anteriores dos produtos NetApp SolidFire e Element"^]

