---
permalink: api/concept_element_api_about_the_api.html 
sidebar: sidebar 
keywords: SolidFire,API,overview,about,Element 
summary: A API Element é baseada no protocolo JSON-RPC em HTTPS. JSON-RPC é um protocolo RPC simples baseado em texto baseado no formato de intercâmbio de dados JSON leve. Bibliotecas de clientes estão disponíveis para todas as principais linguagens de programação. 
---
= Aprenda a gerenciar o armazenamento com a API Element.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A API Element é baseada no protocolo JSON-RPC em HTTPS. JSON-RPC é um protocolo RPC simples baseado em texto baseado no formato de intercâmbio de dados JSON leve. Bibliotecas de clientes estão disponíveis para todas as principais linguagens de programação.

Você pode fazer solicitações de API via HTTPS POST para o endpoint da API. O corpo da SOLICITAÇÃO POST é um objeto de solicitação JSON-RPC. No momento, a API não oferece suporte a solicitações em lote (vários objetos de solicitação em um ÚNICO POST). Ao enviar solicitações de API, você deve usar "Application/JSON-rpc" como o tipo de conteúdo da solicitação e garantir que o corpo não esteja codificado em forma.


NOTE: A IU da Web do Element faz uso dos métodos de API descritos neste documento. Você pode monitorar operações de API na IU habilitando o Registro de API; isso permite que você veja os métodos que estão sendo emitidos para o sistema. Você pode habilitar solicitações e respostas para ver como o sistema responde aos métodos que são emitidos.

Salvo indicação em contrário, todas as strings de data nas respostas da API estão no formato UTC-0.


NOTE: Quando o cluster de armazenamento é carregado fortemente ou você envia muitas solicitações de API consecutivas sem atraso intermediário, um método pode falhar e retornar o erro "xDBVersionMismatch". Se isso acontecer, tente novamente a chamada de método.



== Objetos comuns

A API do software Element usa objetos JSON para representar conceitos de dados organizados. Muitos desses métodos de API usam esses objetos para entrada e saída de dados. Esta seção documenta esses objetos comumente usados; objetos que são usados somente dentro de um único método são documentados com esse método em vez de nesta seção.

link:../api/reference_element_api_account.html["Aprenda sobre objetos comuns"]



== Métodos comuns

Métodos comuns são métodos usados para recuperar informações sobre o cluster de armazenamento, a própria API ou operações de API em curso.

link:../api/reference_element_api_getapi.html["Aprenda sobre métodos comuns"]



== Métodos de API de conta

Os métodos de conta permitem adicionar, remover, exibir e modificar informações de conta e segurança.

link:../api/reference_element_api_addaccount.html["Saiba mais sobre os métodos da API de conta."]



== Métodos da API do administrador

Você pode usar os métodos de API do administrador para criar, modificar, exibir e remover administradores de cluster de storage e atribuir níveis de acesso e Privileges para aqueles com acesso a um cluster de storage.

link:../api/reference_element_api_addclusteradmin.html["Saiba mais sobre os métodos da API de administrador."]



== Métodos de API de cluster

Os métodos de API de cluster de software Element permitem gerenciar a configuração e a topologia do cluster de storage e dos nós que pertencem a um cluster de storage.

Alguns métodos de API de cluster operam em nós que fazem parte de um cluster ou que foram configurados para ingressar em um cluster. Você pode adicionar nós a um novo cluster ou a um cluster existente. Os nós que estão prontos para serem adicionados a um cluster estão em um estado "pendente", o que significa que eles foram configurados, mas ainda não foram adicionados ao cluster.

link:../api/reference_element_api_addnodes.html["Saiba mais sobre os métodos da API de cluster."]



== Métodos da API de criação de clusters

Você pode usar esses métodos de API para criar um cluster de armazenamento. Todos esses métodos precisam ser usados contra o endpoint da API em um único nó.

link:../api/reference_element_api_checkproposedcluster.html["Saiba mais sobre os métodos da API de criação de clusters."]



== Métodos da API da unidade

Você pode usar os métodos de API de unidade para adicionar e gerenciar unidades que estão disponíveis para um cluster de armazenamento. Quando você adiciona um nó de armazenamento ao cluster de armazenamento ou instala novas unidades em um nó de armazenamento existente, as unidades estão disponíveis para serem adicionadas ao cluster de armazenamento.

link:../api/reference_element_api_adddrives.html["Saiba mais sobre os métodos da API Drive."]



== Métodos de API Fibre Channel

Você pode usar os métodos de API Fibre Channel para adicionar, modificar ou remover membros de nós Fibre Channel de um cluster de storage.

link:../api/reference_element_api_getvolumeaccessgrouplunassignments.html["Saiba mais sobre os métodos da API Fibre Channel"]



== Métodos da API do iniciador

Os métodos de iniciador permitem adicionar, remover, visualizar e modificar objetos do iniciador iSCSI, que lidam com a comunicação entre o sistema de armazenamento e clientes de armazenamento externos.

link:../api/reference_element_api_createinitiators.html["Saiba mais sobre os métodos da API do iniciador."]



== Métodos de API LDAP

Você pode usar o LDAP (Lightweight Directory Access Protocol) para autenticar o acesso ao armazenamento de elementos. Os métodos de API LDAP descritos nesta seção permitem configurar o acesso LDAP ao cluster de armazenamento.

link:../api/reference_element_api_addldapclusteradmin.html["Saiba mais sobre os métodos da API LDAP"]



== Métodos de API de autenticação multifator

Você pode usar a autenticação multifator (MFA) para gerenciar sessões de usuários usando um provedor de identidade (IDP) de terceiros por meio da Security Assertion Markup Language (SAML).

link:../api/reference_element_api_addidpclusteradmin.html["Saiba mais sobre os métodos da API de autenticação multifator."]



== Métodos API de autenticação de sessão

Você pode usar autenticação baseada em sessão para gerenciar sessões de usuário.

link:../api/reference_element_api_listauthsessionbyclusteradmin.html["Saiba mais sobre os métodos da API de autenticação de sessão."]



== Métodos de API de nó

Você pode usar métodos de API de nó para configurar nós individuais. Esses métodos operam em nós únicos que precisam ser configurados, configurados, mas ainda não participam de um cluster ou participam ativamente de um cluster. Os métodos de API de nó permitem exibir e modificar configurações de nós individuais e da rede de cluster usada para se comunicar com o nó. É necessário executar esses métodos em nós individuais; não é possível executar métodos de API por nó no endereço do cluster.

link:../api/reference_element_api_checkpingonvlan.html["Aprenda sobre os métodos da API do Node.js"]



== Métodos de API de replicação

Os métodos de API de replicação permitem conectar dois clusters para proteção contínua de dados (CDP). Quando você conecta dois clusters, os volumes ativos em um cluster podem ser replicados continuamente para um segundo cluster a fim de fornecer recuperação de dados. Ao emparelhar volumes para replicação, você pode proteger seus dados de eventos que podem torná-los inacessíveis.

link:../api/reference_element_api_cluster_pairing_order_of_operations.html["Saiba mais sobre os métodos da API de replicação."]



== Métodos de API de segurança

Você pode integrar o software Element com serviços externos relacionados à segurança, como um servidor de gerenciamento de chaves externo. Esses métodos relacionados à segurança permitem configurar recursos de segurança do elemento, como gerenciamento de chaves externas para criptografia em repouso.

link:../api/reference_element_api_addkeyservertoproviderkmip.html["Saiba mais sobre os métodos da API de segurança."]



== Métodos de API do SnapMirror

Os métodos de API do SnapMirror são usados pela IU da Web Element para gerenciar snapshots espelhados com sistemas ONTAP remotos. Esses métodos são destinados apenas para uso pela IU da Web Element. Se você precisar de acesso à API à funcionalidade do SnapMirror, use as APIs do ONTAP. Exemplos de solicitação e retorno não são fornecidos para os métodos de API do SnapMirror.

link:../api/reference_element_api_abortsnapmirrorrelationship.html["Saiba mais sobre os métodos da API do SnapMirror"]



== Métodos de API de configuração do sistema

Os métodos de API de configuração do sistema permitem obter e definir valores de configuração que se aplicam a todos os nós no cluster.

link:../api/reference_element_api_disablebmccoldreset.html["Saiba mais sobre os métodos da API de configuração do sistema."]



== Métodos de API de rede multitenant

A rede multitenant em clusters de armazenamento Element permite que o tráfego entre vários clientes que estão em redes lógicas separadas seja conetado a um cluster de armazenamento de elemento sem roteamento de camada 3.

As conexões com o cluster de armazenamento são segregadas na pilha de rede através do uso da marcação VLAN.



=== Pré-requisitos para configurar uma rede virtual multitenant

* Você deve ter identificado o bloco de endereços IP de rede cliente a ser atribuído às redes virtuais nos nós de storage.
* Você deve ter identificado um endereço IP de rede de armazenamento de cliente (SVIP) para ser usado como um ponto de extremidade para todo o tráfego de armazenamento.




=== Ordem de operações de rede virtual

. Use o método AddVirtualNetwork para provisionar em massa os endereços IP inseridos.
+
Depois de adicionar uma rede virtual, o cluster executa automaticamente as seguintes etapas:

+
** Cada nó de storage cria uma interface de rede virtual.
** Cada nó de armazenamento é atribuído um endereço VLAN para o qual pode ser roteado usando o SVIP virtual.
** Os endereços IP da VLAN persistem em cada nó no caso de uma reinicialização do nó.


. Quando a interface de rede virtual e os endereços VLAN tiverem sido atribuídos, você poderá atribuir o tráfego de rede do cliente ao SVIP virtual.


link:../api/concept_element_api_virtual_network_naming_conventions.html["Aprenda sobre os métodos da API de rede multitenant."]



== Métodos de API de volume

Os métodos de API de volume do software Element permitem gerenciar volumes que residem em um nó de storage. Você pode criar, modificar, clonar e excluir volumes com esses métodos. Você também pode usar métodos de API de volume para coletar e exibir medições de dados para um volume.

link:../api/reference_element_api_cancelclone.html["Saiba mais sobre os métodos da API de volume."]



== Métodos de API do grupo de acesso ao volume

Os métodos de grupo de acesso ao volume permitem adicionar, remover, exibir e modificar grupos de acesso ao volume, que são coleções de volumes que os usuários podem acessar usando iniciadores iSCSI ou Fibre Channel.

link:../api/reference_element_api_addinitiatorstovolumeaccessgroup.html["Saiba mais sobre os métodos da API de grupos de acesso por volume."]



== Métodos de API de instantâneo de volume

Os métodos de API de snapshot de volume do software Element permitem gerenciar snapshots de volume. Você pode criar, modificar, clonar e excluir snapshots de volume usando os métodos de API de snapshot de volume.

link:../api/concept_element_api_snapshots_overview.html["Saiba mais sobre os métodos da API de snapshot de volume."]



== Métodos de API de volume virtual

Os métodos de API de volume virtual do software Element permitem gerenciar volumes virtuais (VVols). Você pode visualizar os vols existentes com esses métodos de API, bem como criar, modificar e excluir contentores de armazenamento de volume virtual. Embora você não possa usar esses métodos para operar em volumes normais, você pode usar os métodos de API de volume normal para listar informações sobre vols.

link:../api/reference_element_api_createstoragecontainer.html["Saiba mais sobre os métodos da API de volumes virtuais."]



== Encontre mais informações

* https://docs.netapp.com/us-en/element-software/index.html["Documentação do software SolidFire e Element"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentação para versões anteriores dos produtos NetApp SolidFire e Element"^]

