---
permalink: api/concept_element_api_ldap_api_methods.html 
sidebar: sidebar 
keywords: ldap,api,methods 
summary: 'Você pode usar o Lightweight Directory Access Protocol (LDAP) para autenticar o acesso ao armazenamento de elementos. Os métodos de API LDAP descritos nesta seção permitem configurar o acesso LDAP ao cluster de armazenamento.' 
---
= Métodos de API LDAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o LDAP (Lightweight Directory Access Protocol) para autenticar o acesso ao armazenamento de elementos. Os métodos de API LDAP descritos nesta seção permitem configurar o acesso LDAP ao cluster de armazenamento.

* xref:reference_element_api_addldapclusteradmin.adoc[AddLdapClusterAdmin]
* xref:reference_element_api_enableldapauthentication.adoc[EnableLdapAuthentication]
* xref:reference_element_api_disableldapauthentication.adoc[DisableLdapAuthentication]
* xref:reference_element_api_getldapconfiguration.adoc[GetLdapConfiguration]
* xref:reference_element_api_testldapauthentication.adoc[TestLdapAuthentication]




== Encontre mais informações

* https://docs.netapp.com/us-en/element-software/index.html["Documentação do software SolidFire e Element"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentação para versões anteriores dos produtos NetApp SolidFire e Element"^]

