---
permalink: api/reference_element_api_getipmiconfig.html 
sidebar: sidebar 
keywords: hardware,sensor,config,configuration,get,getting,getipmiconfig 
summary: Você pode usar o método GetIpmiConfig para recuperar informações do sensor de hardware de sensores que estão em seu nó. 
---
= GetIpmiConfig
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `GetIpmiConfig` método para recuperar informações do sensor de hardware de sensores que estão em seu nó.



== Parâmetro

Este método tem o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo 


 a| 
ChassisType
 a| 
Usado para exibir informações para cada tipo de chassi de nó. Valores possíveis:

* todos: retorna informações do sensor para cada tipo de chassi.
* retorna informações do sensor para um tipo de chassi especificado.

 a| 
cadeia de carateres

|===


== Valores de retorno

Este método tem os seguintes valores de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
Nome do sensor
 a| 
Nome do sensor que foi encontrado.
 a| 
cadeia de carateres



 a| 
UniqueSensorID
 a| 
Identificador exclusivo para o sensor.
 a| 
cadeia de carateres

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "GetIpmiConfig",
  "params": {
     "chassisType"; "all"
     },
  "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
 "id": 1,
   "result": {
     "nodes": [
         {
           "nodeID": 1,
           "result": {
             "ipmiConfig": {
                "C220M4": [
                    {
                     "sensorName": "Fan1A RPM",
                     "uniqueSensorID": "29.1:0xf"
                    },
                    {
                      "sensorName": "Fan1B RPM",
                      "uniqueSensorID": "29.1:0x10"
                    },
                    {
                      "sensorName": "Fan2A RPM",
                      "uniqueSensorID": "29.2:0x11"
                    },
                    {
                      "sensorName": "Fan2B RPM",
                      "uniqueSensorID": "29.2:0x12"
                    },
                    {
                      "sensorName": "Fan3A RPM",
                      "uniqueSensorID": "29.3:0x13"
                    },
                    {
                      "sensorName": "Fan3B RPM",
                      "uniqueSensorID": "29.3:0x14"
                    },
                    {
                      "sensorName": "Fan4A RPM",
                      "uniqueSensorID": "29.4:0x15"
                    },
                    {
                      "sensorName": "Fan4B RPM",
                      "uniqueSensorID": "29.4:0x16"
                    },
                    {
                      "sensorName": "Fan5A RPM",
                      "uniqueSensorID": "29.5:0x17"
                    },
                    {
                      "sensorName": "Fan5B RPM",
                      "uniqueSensorID": "29.5:0x18"
                    },
                    {
                      "sensorName": "Fan6A RPM",
                      "uniqueSensorID": "29.6:0x19"
                    },
                    {
                      "sensorName": "Fan6B RPM",
                      "uniqueSensorID": "29.6:0x1a"
                    },
                    {
                      "sensorName": "Exhaust Temp",
                      "uniqueSensorID": "7.1:0x1"
                    },
                    {
                      "sensorName": "Inlet Temp",
                      "uniqueSensorID": "7.1:0x4"
                    },
                    {
                      "sensorName": "PS1",
                      "uniqueSensorID": "10.1:0x26"
                    },
                    {
                      "sensorName": "PS2",
                      "uniqueSensorID": "10.2:0x2c"
                    }
                ],
                "R620": [
                    {
                      "sensorName": "Fan1A RPM",
                      "uniqueSensorID": "7.1:0x30"
                    },
                    {
                      "sensorName": "Fan1B RPM",
                      "uniqueSensorID": "7.1:0x31"
                    },
                    {
                      "sensorName": "Fan2A RPM",
                      "uniqueSensorID": "7.1:0x32"
                    },
                    {
                      "sensorName": "Fan2B RPM",
                      "uniqueSensorID": "7.1:0x33"
                    },
                    {
                      "sensorName": "Fan3A RPM",
                      "uniqueSensorID": "7.1:0x34"
                    },
                    {
                      "sensorName": "Fan3B RPM",
                      "uniqueSensorID": "7.1:0x35"
                    },
                    {
                      "sensorName": "Fan4A RPM",
                      "uniqueSensorID": "7.1:0x36"
                    },
                    {
                      "sensorName": "Fan4B RPM",
                      "uniqueSensorID": "7.1:0x37"
                    },
                    {
                      "sensorName": "Fan5A RPM",
                      "uniqueSensorID": "7.1:0x38"
                    },
                    {
                      "sensorName": "Fan5B RPM",
                      "uniqueSensorID": "7.1:0x39"
                    },
                    {
                      "sensorName": "Fan6A RPM",
                      "uniqueSensorID": "7.1:0x3a"
                    },
                    {
                      "sensorName": "Fan6B RPM",
                      "uniqueSensorID": "7.1:0x3b"
                    },
                    {
                      "sensorName": "Fan7A RPM",
                      "uniqueSensorID": "7.1:0x3c"
                    },
                    {
                      "sensorName": "Fan7B RPM",
                      "uniqueSensorID": "7.1:0x3d"
                    },
                    {
                      "sensorName": "Exhaust Temp",
                      "uniqueSensorID": "7.1:0x1"
                    },
                    {
                      "sensorName": "Inlet Temp",
                      "uniqueSensorID": "7.1:0x4"
                    },
                    {
                      "sensorName": "PS1",
                      "uniqueSensorID": "10.1:0x62"
                    },
                    {
                      "sensorName": "PS2",
                      "uniqueSensorID": "10.2:0x63"
                    }
               ],
          }
----


== Novo desde a versão

9,6
