---
permalink: api/reference_element_api_setlldpconfig.html 
sidebar: sidebar 
keywords: lldp,config,configure,set,setting,setlldpconfig 
summary: 'Você pode usar o método SetLldpConfig para configurar as configurações do protocolo de descoberta de camada de link (LLDP) para um cluster de armazenamento.' 
---
= SetLldpConfig
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `SetLldpConfig` método para configurar as configurações do Protocolo de descoberta de camada de enlace (LLDP) para um cluster de armazenamento.



== Parâmetros

Este método tem os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
EnableOtherProtocols
 a| 
Ativar a utilização automática de outros protocolos de deteção - CDP, FDP, EDP e SONMP.
 a| 
booleano
 a| 
verdadeiro
 a| 
Não



 a| 
EnableMed
 a| 
Ativar a descoberta de endpoints multimédia (LLDP-meD).
 a| 
booleano
 a| 
falso
 a| 
Não



 a| 
EnableLldp
 a| 
Ativar ou desativar o LLDP.
 a| 
booleano
 a| 
verdadeiro
 a| 
Não

|===


== Valores de retorno

Este método tem o seguinte valor de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
LldpConfig
 a| 
Informações sobre a configuração atual do LLDP do cluster de armazenamento, incluindo as configurações recém-alteradas.
 a| 
Objeto JSON

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "id": 3920,
  "method":"SetLldpConfig",
    "params": {
        "lldpConfig": {
            "enableMed": true
        }
    }
  }
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
  "id": 3920,
  "result": {
    "lldpConfig": {
        "enableLldp": true,
        "enableMed": true,
        "enableOtherProtocols": true
     }
  }
}
----