---
permalink: api/reference_element_api_listdrivestats.html 
sidebar: sidebar 
keywords: cluster,list,listing,drive,drives,stats,statistics,listdrivestats 
summary: Você pode usar o método ListDriveStats para listar medições de atividade de alto nível para várias unidades no cluster. Por padrão, este método retorna estatísticas para todas as unidades no cluster, e essas medições são cumulativas da adição da unidade ao cluster. Alguns valores que este método retorna são específicos para blocos de unidades, e alguns são específicos para unidades de metadados. 
---
= ListDriveStats
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pode utilizar o `ListDriveStats` método para listar medições de atividade de alto nível para várias unidades no cluster. Por padrão, este método retorna estatísticas para todas as unidades no cluster, e essas medições são cumulativas da adição da unidade ao cluster. Alguns valores que este método retorna são específicos para blocos de unidades, e alguns são específicos para unidades de metadados.



== Parâmetro

Este método tem o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
unidades
 a| 
Lista de IDs de unidade (driveID) para os quais devolver estatísticas de condução. Se você omitir esse parâmetro, as medidas de todas as unidades serão retornadas.
 a| 
array inteiro
 a| 
Nenhum
 a| 
Não

|===


== Valores de retorno

Este método tem os seguintes valores de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
DriveStats
 a| 
Lista de informações sobre a atividade da unidade para cada unidade.
 a| 
xref:reference_element_api_drivestats.adoc[DriveStats] array



 a| 
erros
 a| 
Esta lista contém o driveID e a mensagem de erro associada. Está sempre presente, e vazio se não houver erros.
 a| 
Array de objetos JSON

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "id": 1,
  "method": "ListDriveStats",
  "params": {
    "drives":[22,23]
  }
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
  "id": 1,
  "result": {
    "driveStats": [
      {
        "driveID": 22,
        "failedDieCount": 0,
        "lifeRemainingPercent": 84,
        "lifetimeReadBytes": 30171004403712,
        "lifetimeWriteBytes": 103464755527680,
        "powerOnHours": 17736,
        "readBytes": 14656542,
         "readOps": 3624,
        "reallocatedSectors": 0,
        "reserveCapacityPercent": 100,
        "timestamp": "2016-03-01T00:19:24.782735Z",
        "totalCapacity": 300069052416,
        "usedCapacity": 1783735635,
        "usedMemory": 879165440,
        "writeBytes": 2462169894,
        "writeOps": 608802
      }
    ],
    "errors": [
      {
        "driveID": 23,
        "exception": {
          "message": "xStatCheckpointDoesNotExist",
          "name": "xStatCheckpointDoesNotExist"
        }
      }
    ]
  }
}
----


== Novo desde a versão

9,6



== Encontre mais informações

xref:reference_element_api_getdrivestats.adoc[GetDriveStats]
