---
permalink: api/reference_element_api_listallnodes.html 
sidebar: sidebar 
keywords: cluster,list,listing,node,nodes,all,listallnodes 
summary: Você pode usar o método ListAllNodes para listar os nós ativos e pendentes no cluster. 
---
= ListAllNodes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ListAllNodes` método para listar nós ativos e pendentes no cluster.



== Parâmetros

Este método não tem parâmetros de entrada.



== Valores de retorno

Este método tem os seguintes valores de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
nós
 a| 
Lista de objetos que descrevem nós ativos no cluster.
 a| 
xref:reference_element_api_node.adoc[nó]



 a| 
PentingActiveNodes
 a| 
Lista de objetos que descrevem nós ativos pendentes para o cluster.
 a| 
xref:reference_element_api_pendingactivenode.adoc[PendingActiveNode] array



 a| 
PendingNodes
 a| 
Lista de objetos que descrevem nós pendentes para o cluster.
 a| 
xref:reference_element_api_pendingnode.adoc[PendingNode] array

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "ListAllNodes",
   "params": {},
   "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
	"id": 1,
	"result": {
		"nodes": [
			{
				"associatedFServiceID": 0,
				"associatedMasterServiceID": 1,
				"attributes": {},
				"chassisName": "CT5TV12",
				"cip": "10.1.1.1",
				"cipi": "Bond10G",
				"fibreChannelTargetPortGroup": null,
				"mip": "10.1.1.1",
				"mipi": "Bond1G",
				"name": "NLABP0704",
				"nodeID": 1,
				"nodeSlot": "",
				"platformInfo": {
					"chassisType": "R620",
					"cpuModel": "Intel",
					"nodeMemoryGB": 72,
					"nodeType": "SF3010",
					"platformConfigVersion": "0.0.0.0"
				},
				"sip": "10.1.1.1",
				"sipi": "Bond10G",
				"softwareVersion": "11.0",
				"uuid": "4C4C4544-0054",
				"virtualNetworks": []
			}
		],
		"pendingActiveNodes": [],
		"pendingNodes": []
	}
}
----


== Novo desde a versão

9,6
