---
permalink: api/reference_element_api_deleteauthsessionsbyusername.html 
sidebar: sidebar 
keywords: auth sessions,username,delete,authentication sessions 
summary: Você pode usar o método DeleteAuthSessionsByUsername para excluir todas as sessões de autenticação de um determinado usuário. Um chamador que não esteja no Access Group ClusterAdmins/Administrator só pode excluir suas próprias sessões. Um chamador com ClusterAdmins/Administrator Privileges pode excluir sessões pertencentes a qualquer usuário. Para ver a lista de sessões que podem ser excluídas, use ListAuthSessionsByUsername com os mesmos parâmetros. Para exibir uma lista de sessões para possível exclusão, use o método ListAuthSessionsByUsername com o mesmo parâmetro. 
---
= DeleteAuthSessionsByUsername
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `DeleteAuthSessionsByUsername` método para excluir todas as sessões de autenticação de um determinado usuário(s). Um chamador que não esteja no Access Group ClusterAdmins/Administrator só pode excluir suas próprias sessões. Um chamador com ClusterAdmins/Administrator Privileges pode excluir sessões pertencentes a qualquer usuário. Para ver a lista de sessões que podem ser excluídas, use `ListAuthSessionsByUsername` com os mesmos parâmetros. Para visualizar uma lista de sessões para possível eliminação, utilize o `ListAuthSessionsByUsername` método com o mesmo parâmetro.



== Parâmetros

Este método tem os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
AuthMethod
 a| 
Método de autenticação das sessões do utilizador a eliminar. Somente um chamador no ClusterAdmins/Administrator AccessGroup pode fornecer este parâmetro. Os valores possíveis são:

* Especifica o nome de usuário do ClusterAdmin.
* Especifica o DN LDAP do usuário.
* * Especifica o UUUID IDP do usuário ou o NameID do usuário. Se o IDP não estiver configurado para retornar qualquer opção, isso especifica um UUID aleatório emitido quando a sessão foi criada.

 a| 
AuthMethod
 a| 
Nenhum
 a| 
Não



 a| 
nome de utilizador
 a| 
Identificador exclusivo para o utilizador.
 a| 
cadeia de carateres
 a| 
Nenhum
 a| 
Não

|===


== Valores de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
sessões
 a| 
Informações de sessão para as sessões de autenticação excluídas.
 a| 
link:reference_element_api_authsessioninfo.html["AuthSessionInfo"]

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "DeleteAuthSessionsByUsername",
  "params": {
    "authMethod": "Cluster",
    "username": "admin"
  }
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
"sessions": [
      {
        "accessGroupList": [
          "administrator"
        ],
        "authMethod": "Cluster",
        "clusterAdminIDs": [
          1
        ],
        "finalTimeout": "2020-03-14T19:21:24Z",
        "idpConfigVersion": 0,
        "lastAccessTimeout": "2020-03-11T19:51:24Z",
        "sessionCreationTime": "2020-03-11T19:21:24Z",
        "sessionID": "b12bfc64-f233-44df-8b9f-6fb6c011abf7",
        "username": "admin"
      }
    ]
}
----


== Novo desde a versão

12,0
