---
permalink: api/reference_element_api_addkeyservertoproviderkmip.html 
sidebar: sidebar 
keywords: KMIP,key server,assigning to key provider,assign,addkeyservertoproviderkmip 
summary: 'Você pode usar o método AddKeyServerToProviderKmip para atribuir um servidor de chave KMIP (Key Management Interoperability Protocol) ao provedor de chaves especificado. Durante a atribuição, o servidor é contatado para verificar a funcionalidade. Se o servidor de chaves especificado já estiver atribuído ao provedor de chaves especificado, nenhuma ação será tomada e nenhum erro será retornado. Você pode remover a atribuição usando o método RemveKeyServerFromProviderKmip.' 
---
= AddKeyServerToProviderKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `AddKeyServerToProviderKmip` método para atribuir um servidor de chave KMIP (Key Management Interoperability Protocol) ao provedor de chaves especificado. Durante a atribuição, o servidor é contatado para verificar a funcionalidade. Se o servidor de chaves especificado já estiver atribuído ao provedor de chaves especificado, nenhuma ação será tomada e nenhum erro será retornado. Você pode remover a atribuição usando o `RemoveKeyServerFromProviderKmip` método.



== Parâmetros

Este método tem os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
KeyProviderID
 a| 
A ID do provedor de chaves para atribuir o servidor de chaves.
 a| 
número inteiro
 a| 
Nenhum
 a| 
Sim



 a| 
KeyServerID
 a| 
A ID do servidor de chaves a atribuir.
 a| 
número inteiro
 a| 
Nenhum
 a| 
Sim

|===


== Valores de retorno

Este método não tem valor de retorno. A atribuição é considerada bem-sucedida, desde que não haja nenhum erro retornado.



== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "AddKeyServerToProviderKmip",
  "params": {
    "keyProviderID": 1,
    "keyServerID": 15
    },
"id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
   "id": 1,
   "result":
      {}
    }
}
----


== Novo desde a versão

11,7
