---
permalink: api/reference_element_api_creategroupsnapshot.html 
sidebar: sidebar 
keywords: volume,volumes,snapshot,snapshots,CreateGroupSnapshot,group,create,creating 
summary: Você pode usar o CreateGroupSnapshot para criar uma cópia pontual de um grupo de volumes. 
---
= CreateGroupSnapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar `CreateGroupSnapshot` para criar uma cópia pontual de um grupo de volumes.

Você pode usar esse snapshot mais tarde como um backup ou reversão para garantir que os dados no grupo de volumes sejam consistentes para o ponto no tempo em que você criou o snapshot.

*CLUSTER_FULLNESS*


NOTE: Você pode criar snapshots se a plenitude do cluster estiver na fase 1, 2 ou 3. Não é possível criar instantâneos quando a plenitude do cluster atinge a fase 4 ou 5.



== Parâmetros

Este método tem os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
`attributes`
 a| 
Lista de pares nome-valor no formato de objeto JSON.
 a| 
Objeto JSON
 a| 
Nenhum
 a| 
Não



 a| 
`enableRemoteReplication`
 a| 
Especifica se o instantâneo será replicado para o armazenamento remoto ou não. Valores possíveis:

* `true`: O instantâneo será replicado para o armazenamento remoto.
* `false`: O instantâneo não será replicado para o armazenamento remoto.

 a| 
booleano
 a| 
falso
 a| 
Não



| `ensureSerialCreation`  a| 
Especifica que o snapshot não deve ser criado se uma replicação anterior de snapshot estiver em andamento. Os valores possíveis são:

* `true`: Isso garante que apenas um snapshot esteja sendo replicado de cada vez. A criação de um novo snapshot falhará se uma replicação anterior de snapshot ainda estiver em andamento.
* `false`: Predefinição. Esta criação de instantâneos é permitida se outra replicação de instantâneos ainda estiver em andamento.

| booleano | `false` | Não 


 a| 
`expirationTime`
 a| 
Especifique o tempo após o qual o instantâneo pode ser removido. Não pode ser utilizado com `retention`. Se nenhuma das `expirationTime`opções , ou `retention` for especificada, a captura instantânea não expirará. O formato de hora é uma string de data ISO 8601 para expiração baseada em tempo, caso contrário não expirará. Um valor de `null` faz com que o instantâneo seja mantido permanentemente. Um valor de `fifo` faz com que o snapshot seja preservado em uma base de primeiro em primeiro em primeiro em primeiro em primeiro em primeiro em primeiro lugar (FIFO), em relação a outros snapshots FIFO no volume. A API falhará se nenhum espaço FIFO estiver disponível.
 a| 
String de data ISO 8601
 a| 
Nenhum
 a| 
Não



 a| 
`name`
 a| 
O nome do instantâneo do grupo. Se não for introduzido nenhum nome, é utilizada a data e a hora em que o instantâneo do grupo foi tirado. O comprimento máximo permitido do nome é de 255 carateres.
 a| 
cadeia de carateres
 a| 
Nenhum
 a| 
Não



 a| 
`retention`
 a| 
Este parâmetro é o mesmo que o `expirationTime` parâmetro, exceto que o formato de hora é HH:mm:ss. Se não `expirationTime` forem especificados nem `retention`, o instantâneo não expirará.
 a| 
cadeia de carateres
 a| 
Nenhum
 a| 
Não



 a| 
`snapMirrorLabel`
 a| 
O rótulo usado pelo software SnapMirror para especificar a política de retenção de snapshot em um endpoint do SnapMirror.
 a| 
cadeia de carateres
 a| 
Nenhum
 a| 
Não



 a| 
`volumes`
 a| 
ID exclusiva da imagem de volume a partir da qual copiar.
 a| 
Array volumeID
 a| 
Nenhum
 a| 
Sim

|===


== Valores de retorno

Este método tem os seguintes valores de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
membros
 a| 
Lista de checksum, volumeIDs e snapshotIDs para cada membro do grupo. Valores válidos:

* Checksum: Uma pequena representação de cadeia de carateres dos dados no instantâneo armazenado. Esta soma de verificação pode ser usada mais tarde para comparar outros instantâneos para detetar erros nos dados. (string)
* SnapshotID: ID exclusivo de um instantâneo a partir do qual o novo instantâneo é feito. O snapshotID deve ser de um instantâneo no volume dado. (número inteiro)
* VolumeID: O ID do volume de origem para o instantâneo. (número inteiro)

 a| 
Array de objetos JSON



 a| 
GroupSnapshotID
 a| 
ID exclusiva do novo instantâneo do grupo.
 a| 
ID do GroupSnapshot



 a| 
GroupSnapshot
 a| 
Objeto contendo informações sobre o instantâneo de grupo recém-criado.
 a| 
xref:reference_element_api_groupsnapshot.adoc[GroupSnapshot]

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "CreateGroupSnapshot",
   "params": {
      "volumes": [1,2]
   },
   "id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
  "id": 1,
  "result": {
    "groupSnapshot": {
      "attributes": {},
      "createTime": "2016-04-04T22:43:29Z",
      "groupSnapshotID": 45,
      "groupSnapshotUUID": "473b78a3-ef85-4541-9438-077306b2d3ca",
      "members": [
        {
          "attributes": {},
          "checksum": "0x0",
          "createTime": "2016-04-04T22:43:29Z",
          "enableRemoteReplication": false,
          "expirationReason": "None",
          "expirationTime": null,
          "groupID": 45,
          "groupSnapshotUUID": "473b78a3-ef85-4541-9438-077306b2d3ca",
          "name": "2016-04-04T22:43:29Z",
          "snapshotID": 3323,
          "snapshotUUID": "7599f200-0092-4b41-b362-c431551937d1",
          "status": "done",
          "totalSize": 5000658944,
          "virtualVolumeID": null,
          "volumeID": 1
        },
        {
          "attributes": {},
          "checksum": "0x0",
          "createTime": "2016-04-04T22:43:29Z",
          "enableRemoteReplication": false,
          "expirationReason": "None",
          "expirationTime": null,
          "groupID": 45,
          "groupSnapshotUUID": "473b78a3-ef85-4541-9438-077306b2d3ca",
          "name": "2016-04-04T22:43:29Z",
          "snapshotID": 3324,
          "snapshotUUID": "a0776a48-4142-451f-84a6-5315dc37911b",
          "status": "done",
          "totalSize": 6001000448,
          "virtualVolumeID": null,
          "volumeID": 2
        }
      ],
      "name": "2016-04-04T22:43:29Z",
      "status": "done"
    },
    "groupSnapshotID": 45,
    "members": [
      {
        "checksum": "0x0",
        "snapshotID": 3323,
        "snapshotUUID": "7599f200-0092-4b41-b362-c431551937d1",
        "volumeID": 1
      },
      {
        "checksum": "0x0",
        "snapshotID": 3324,
        "snapshotUUID": "a0776a48-4142-451f-84a6-5315dc37911b",
        "volumeID": 2
      }
    ]
  }
}
----


== Novo desde a versão

9,6
