---
permalink: api/reference_element_api_removeclusterpair.html 
sidebar: sidebar 
keywords: cluster,clusters,pair,remove,removing,removeclusterpair 
summary: Você pode usar o método RemoveClusterPair para fechar as conexões abertas entre dois clusters emparelhados. 
---
= RemoveClusterPair
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `RemoveClusterPair` método para fechar as conexões abertas entre dois clusters emparelhados.



== Parâmetro


NOTE: Antes de remover um par de cluster, primeiro é necessário remover todo o emparelhamento de volume com os clusters com o método da API RemoveVolumePair.

Este método tem o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
ClausterPairID
 a| 
Identificador exclusivo usado para emparelhar dois clusters.
 a| 
número inteiro
 a| 
Nenhum
 a| 
Sim

|===


== Valor de retorno

Este método não tem valor de retorno.



== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "RemoveClusterPair",
   "params": {
              "clusterPairID": 1
      },
   "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
   "id": 1,
   "result": {}
}
----


== Novo desde a versão

9,6
