---
permalink: api/reference_element_api_modifyclusterinterfacepreference.html 
sidebar: sidebar 
keywords: modify,modifying,edit,editing,change,changing,cluster,interface,preference,modifyclusterinterfacepreference 
summary: O método ModifyClusterInterfacePreference permite que sistemas integrados com clusters de armazenamento que executam o software Element alterem uma preferência de interface de cluster existente. Este método é para uso interno. 
---
= ModifyClusterInterfacePreference
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esse `ModifyClusterInterfacePreference` método permite que sistemas integrados a clusters de storage que executam o software Element alterem uma preferência de interface de cluster existente. Este método é para uso interno.



== Parâmetros

Este método tem os seguintes parâmetros de entrada:

|===


| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
nome
 a| 
O nome da preferência de interface de cluster a modificar.
 a| 
cadeia de carateres
 a| 
Nenhum
 a| 
Sim



 a| 
valor
 a| 
O novo valor da preferência de interface de cluster.
 a| 
cadeia de carateres
 a| 
Nenhum
 a| 
Sim

|===


== Valores de retorno

Este método não tem valores de retorno.



== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
	"method": "ModifyClusterInterfacePreference",
	"params": {
	"name": "testname",
	"value": "newvalue"
},
	"id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
    "id": 1,
    "result": {}
}
----


== Novo desde a versão

11,0
