---
permalink: api/reference_element_api_listnetworkinterfaces.html 
sidebar: sidebar 
keywords: network,interface,interfaces,list,listing,listnetworkinterfaces 
summary: Você pode usar o método ListNetworkInterfaces para listar informações sobre cada interface de rede em um nó. Este método de API destina-se a ser utilizado em nós individuais; a autenticação de ID de utilizador e palavra-passe é necessária para o acesso a nós individuais. No entanto, você pode usar esse método no cluster se a força de parâmetro for dada o valor verdadeiro na chamada de método. Quando o parâmetro é usado no cluster, todas as interfaces são listadas. 
---
= ListNetworkInterfaces
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ListNetworkInterfaces` método para listar informações sobre cada interface de rede em um nó. Este método de API destina-se a ser utilizado em nós individuais; a autenticação de ID de utilizador e palavra-passe é necessária para o acesso a nós individuais. No entanto, você pode usar esse método no cluster se a força de parâmetro for dada o valor verdadeiro na chamada de método. Quando o parâmetro é usado no cluster, todas as interfaces são listadas.



== Parâmetro

Este método tem o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
força
 a| 
Valores possíveis:

* Verdadeiro: As informações sobre todas as interfaces de rede no cluster são retornadas.
* Falso: Nenhuma informação é retornada.

 a| 
booleano
 a| 
Nenhum
 a| 
Não

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
interfaces
 a| 
Uma lista de informações de configuração para cada interface de rede do nó de armazenamento (ou todo o cluster de armazenamento, se for `true`
 a| 
xref:reference_element_api_networkinterface.adoc[NetworkInterface] array

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
"method": "ListNetworkInterfaces",
"params": {},
"id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
	"id": 1,
	"result": {
		"nodes": [
			{
				"nodeID": 1,
				"result": {
					"interfaces": [
						{
							"address": "10.117.80.32",
							"addressV6": "::",
							"broadcast": "10.117.95.255",
							"macAddress": "90:b1:1c:42:e0:1a",
							"mtu": 9000,
							"name": "Bond10G",
							"namespace": false,
							"netmask": "255.255.240.0",
							"status": "UpAndRunning",
							"type": "BondMaster",
							"virtualNetworkTag": 0
						},
						{
							"address": "10.117.64.32",
							"addressV6": "::",
							"broadcast": "10.117.79.255",
							"macAddress": "90:b1:1c:42:e0:1e",
							"mtu": 1500,
							"name": "Bond1G",
							"namespace": false,
							"netmask": "255.255.240.0",
							"status": "UpAndRunning",
							"type": "BondMaster",
							"virtualNetworkTag": 0
						},
						{
							"address": "0.0.0.0",
							"addressV6": "::",
							"broadcast": "0.0.0.0",
							"macAddress": "90:b1:1c:42:e0:1a",
							"mtu": 9000,
							"name": "eth0",
							"namespace": false,
							"netmask": "0.0.0.0",
							"status": "UpAndRunning",
							"type": "BondSlave",
							"virtualNetworkTag": 0
						},
						{
							"address": "127.0.0.1",
							"addressV6": "::",
							"broadcast": "0.0.0.0",
							"macAddress": "00:00:00:00:00:00",
							"mtu": 0,
							"name": "lo",
							"namespace": false,
							"netmask": "0.0.0.0",
							"status": "UpAndRunning",
							"type": "Loopback",
							"virtualNetworkTag": 0
						}
					]
				}
			}
		]
	}
}
----


== Novo desde a versão

9,6
