---
permalink: api/reference_element_api_listpendingactivenodes.html 
sidebar: sidebar 
keywords: cluster,list,listing,pending,active,node,nodes,listpendingactivenodes 
summary: Você pode usar o método ListPendingActiveNodes para listar os nós no cluster que estão no estado PendingActive, entre os estados pendente e ativo. Nós neste estado estão sendo retornados à imagem de fábrica. 
---
= ListPendingActiveNodes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ListPendingActiveNodes` método para listar nós no cluster que estão no estado PendingActive, entre estados pendentes e ativos. Nós neste estado estão sendo retornados à imagem de fábrica.



== Parâmetros

Este método não tem parâmetros de entrada.



== Valor de retorno

Este método tem o seguinte valor de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
PentingActiveNodes
 a| 
Lista de objetos detalhando informações sobre todos os nós PendingActive no sistema.
 a| 
xref:reference_element_api_pendingactivenode.adoc[PendingActiveNode] array

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "ListPendingActiveNodes",
   "params": {},
   "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
  id: null,
  result: {
    pendingActiveNodes: [
    {
      activeNodeKey: "5rPHP3lTAO",
      assignedNodeID: 5,
      asyncHandle: 2,
      cip: "10.10.5.106",
      mip: "192.168.133.106",
      pendingNodeID: 1,
      platformInfo: {
        chassisType: "R620",
        cpuModel: "Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz",
        nodeMemoryGB: 72,
        nodeType: "SF3010"
      },
     sip: "10.10.5.106",
     softwareVersion: "9.0.0.1077"
    }
    ]
  }
}
----


== Novo desde a versão

9,6
