---
permalink: api/reference_element_api_createqospolicy.html 
sidebar: sidebar 
keywords: QoS,policy,policies,create,creating 
summary: Você pode usar o método CreateQoSPolicy para criar um objeto QoSPolicy que você pode aplicar posteriormente a um volume após a criação ou modificação. Uma política de QoS tem uma ID exclusiva, um nome e definições de QoS. 
---
= CreateQoSPolicy
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `CreateQoSPolicy` método para criar um objeto QoSPolicy que você pode aplicar posteriormente a um volume após a criação ou modificação. Uma política de QoS tem uma ID exclusiva, um nome e definições de QoS.



== Parâmetros

Este método tem os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
nome
 a| 
O nome da política de QoS; por exemplo, ouro, platina ou prata.
 a| 
cadeia de carateres
 a| 
Nenhum
 a| 
Sim



 a| 
qos
 a| 
As definições de QoS que esta política representa.
 a| 
xref:reference_element_api_qos.adoc[QoS]
 a| 
Nenhum
 a| 
Sim

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
QosPolicy
 a| 
O novo objeto QoSPolicy criado.
 a| 
xref:reference_element_api_qospolicy.adoc[Política de qualidade de vida]

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "id": 68,
  "method": "CreateQoSPolicy",
  "params": {
    "name": "bronze",
    "qos": {
      "minIOPS": 50,
      "maxIOPS": 15000,
      "burstIOPS": 15000
    }
  }
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
  "id": 68,
  "result": {
    "qosPolicy": {
      "name": "bronze",
      "qos": {
        "burstIOPS": 15000,
        "burstTime": 60,
        "curve": {
          "4096": 100,
          "8192": 160,
          "16384": 270,
          "32768": 500,
          "65536": 1000,
          "131072": 1950,
          "262144": 3900,
          "524288": 7600,
          "1048576": 15000
        },
        "maxIOPS": 15000,
        "minIOPS": 50
      },
      "qosPolicyID": 2,
      "volumeIDs": []
    }
  }
}
----


== Novo desde a versão

10,0
