---
permalink: api/reference_element_api_initializesnapmirrorrelationship.html 
sidebar: sidebar 
keywords: snapmirror,relationship,relationships,initialize,initializing,initializesnapmirrorrelationship 
summary: A IU da Web do software Element usa o método InitializeSnapMirrorRelationship para inicializar o volume de destino em uma relação SnapMirror executando uma transferência inicial da linha de base entre clusters. 
---
= Inicializar SnapMirrorRelacionship
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A IU da Web do software Element usa o `InitializeSnapMirrorRelationship` método para inicializar o volume de destino em uma relação do SnapMirror executando uma transferência inicial da linha de base entre clusters.



== Parâmetros

Este método tem os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
SnapMirrorEndpointID
 a| 
A ID do sistema ONTAP remoto.
 a| 
número inteiro
 a| 
Nenhum
 a| 
Sim



 a| 
Destinaçãovolume
 a| 
O volume de destino na relação SnapMirror.
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[SnapMirrorVolumeInfo]
 a| 
Nenhum
 a| 
Sim



 a| 
MaxTransferRate
 a| 
Especifica a taxa máxima de transferência de dados entre os volumes em kilobytes por segundo. O valor padrão, 0, é ilimitado e permite que o relacionamento SnapMirror utilize totalmente a largura de banda de rede disponível.
 a| 
número inteiro
 a| 
Nenhum
 a| 
Não

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
SnapMirrorRelacionship
 a| 
Informações sobre a relação SnapMirror inicializada.
 a| 
xref:reference_element_api_snapmirrorrelationship.adoc[SnapMirrorRelacionship]

|===


== Novo desde a versão

10,1
