---
permalink: api/reference_element_api_listnodefibrechannelportinfo.html 
sidebar: sidebar 
keywords: list,listing,node,fibre,channel,port,info,listnodefibrechannelportinfo 
summary: Você pode usar o método ListNodeFibreChannelPortInfo para listar informações sobre as portas Fibre Channel em um nó. 
---
= ListNodeFibreChannelPortInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ListNodeFibreChannelPortInfo` método para listar informações sobre as portas Fibre Channel em um nó.

Este método de API destina-se a ser utilizado em nós individuais; um ID de utilizador e uma palavra-passe são necessários para aceder a nós de canal de fibra individuais. Quando usado no cluster, todas as interfaces Fibre Channel são listadas.



== Parâmetro

Este método não tem parâmetros de entrada.



== Valor de retorno

Este método tem o seguinte valor de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
FibreChannelPorts
 a| 
Uma lista de todas as portas Fibre Channel físicas ou uma porta para um único nó.
 a| 
xref:reference_element_api_fibrechannelport.adoc[FibreChannelPort] array

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "ListNodeFibreChannelPortInfo",
   "params": {
       "nodeID": 5,
       "force": true
   },
   "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
  "id": 1,
  "result": {
    "fibreChannelPorts": [
      {
        "firmware": "7.04.00 (d0d5)",
        "hbaPort": 1,
        "model": "QLE2672",
        "nPortID": "0xc7002c",
        "pciSlot": 3,
        "serial": "BFE1335E03500",
        "speed": "8 Gbit",
        "state": "Online",
        "switchWwn": "20:01:00:2a:6a:98:a3:41",
        "wwnn": "5f:47:ac:c8:35:54:02:00",
        "wwpn": "5f:47:ac:c0:35:54:02:02"
      },
      {
         "firmware": "7.04.00 (d0d5)",
         "hbaPort": 2,
         "model": "QLE2672",
         "nPortID": "0x06002d",
         "pciSlot": 3,
         "serial": "BFE1335E03500",
         "speed": "8 Gbit",
         "state": "Online",
         "switchWwn": "20:01:00:2a:6a:9c:71:01",
         "wwnn": "5f:47:ac:c8:35:54:02:00",
         "wwpn": "5f:47:ac:c0:35:54:02:03"
      },
      {
         "firmware": "7.04.00 (d0d5)",
         "hbaPort": 1,
         "model": "QLE2672",
         "nPortID": "0xc7002a",
         "pciSlot": 2,
         "serial": "BFE1335E04029",
         "speed": "8 Gbit",
         "state": "Online",
         "switchWwn": "20:01:00:2a:6a:98:a3:41",
         "wwnn": "5f:47:ac:c8:35:54:02:00",
         "wwpn": "5f:47:ac:c0:35:54:02:00"
     },
     {
         "firmware": "7.04.00 (d0d5)",
         "hbaPort": 2,
         "model": "QLE2672",
         "nPortID": "0x06002a",
         "pciSlot": 2,
         "serial": "BFE1335E04029",
         "speed": "8 Gbit",
         "state": "Online",
         "switchWwn": "20:01:00:2a:6a:9c:71:01",
         "wwnn": "5f:47:ac:c8:35:54:02:00",
         "wwpn": "5f:47:ac:c0:35:54:02:01"
      }
    ]
  }
}
----


== Novo desde a versão

9,6
