---
permalink: api/reference_element_api_listsnapshots.html 
sidebar: sidebar 
keywords: snapshot,snapshots,list,listing,attributes,listsnapshots 
summary: Você pode usar ListSnapshots para retornar os atributos de cada snapshot captado no volume. 
---
= ListSnapshots
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar `ListSnapshots` para retornar os atributos de cada snapshot captado no volume.

As informações sobre instantâneos que residem no cluster de destino serão exibidas no cluster de origem quando este método for chamado a partir do cluster de origem.



== Parâmetros

Este método tem os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
VolumeID
 a| 
Recupera instantâneos para um volume. Se o volumeID não for fornecido, todos os instantâneos de todos os volumes serão retornados.
 a| 
número inteiro
 a| 
Nenhum
 a| 
Não



 a| 
SnapshotID
 a| 
Recupera informações para um ID de instantâneo individual.
 a| 
número inteiro
 a| 
Nenhum
 a| 
Não

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
instantâneos
 a| 
Informações sobre cada instantâneo para cada volume. Se o volumeID não for fornecido, todos os instantâneos de todos os volumes serão retornados. Os instantâneos que estão em um grupo são retornados com um ID de grupo.
 a| 
xref:reference_element_api_snapshot.adoc[snapshot] array

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "ListSnapshots",
   "params": {
             "volumeID": "1"
       },
   "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
  "id": 1,
  "result": {
    "snapshots": [
        {
          "attributes": {},
          "checksum": "0x0",
          "createTime": "2015-05-08T13:15:00Z",
          "enableRemoteReplication": true,
          "expirationReason": "None",
          "expirationTime": "2015-05-08T21:15:00Z",
          "groupID": 0,
          "groupSnapshotUUID": "00000000-0000-0000-0000-000000000000",
          "name": "Hourly",
          "remoteStatuses": [
              {
                "remoteStatus": "Present",
                "volumePairUUID": "237e1cf9-fb4a-49de-a089-a6a9a1f0361e"
              }
         ],
          "snapshotID": 572,
          "snapshotUUID": "efa98e40-cb36-4c20-a090-a36c48296c14",
          "status": "done",
          "totalSize": 10000269312,
          "volumeID": 1
        }
      ]
    }
  }
----


== Novo desde a versão

9,6
