---
permalink: api/reference_element_api_listactivevolumes.html 
sidebar: sidebar 
keywords: active,volume,volumes,list,listing,listactivevolumes,cluster 
summary: 'Você pode usar o método ListActiveVolumes para obter a lista de volumes ativos atualmente no sistema. A lista de volumes é ordenada na ordem VolumeID e pode ser devolvida em várias partes (páginas).' 
---
= ListActiveVolumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ListActiveVolumes` método para obter a lista de volumes ativos atualmente no sistema. A lista de volumes é ordenada por ordem VolumeID e pode ser devolvida em várias partes (páginas).



== Parâmetros

Este método tem os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
IncludeVirtualVolumes
 a| 
Os volumes virtuais são incluídos na resposta, por padrão. Para excluir volumes virtuais, defina como false.
 a| 
booleano
 a| 
verdadeiro
 a| 
Não



 a| 
StartVolumeID
 a| 
Iniciar VolumeID para regressar. Se não existir nenhum volume com este VolumeID, o volume seguinte por ordem VolumeID é utilizado como o início da lista. Para percorrer a lista, passe o VolumeID do último volume na resposta anterior e 1.
 a| 
número inteiro
 a| 
0
 a| 
Não



 a| 
limite
 a| 
Número máximo de objetos de informações de volume a serem retornados. 0 (zero) retorna todos os volumes (ilimitado).
 a| 
número inteiro
 a| 
(ilimitado)
 a| 
Não

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
volumes
 a| 
Lista de volumes ativos.
 a| 
xref:reference_element_api_volume.adoc[volume] array

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "ListActiveVolumes",
   "params": {
      "startVolumeID"  : 0,
      "limit" : 1000
   },
   "id" : 1
}
----


== Exemplo de resposta

Devido ao tamanho deste exemplo de resposta, ele está documentado em um tópico suplementar.



== Novo desde a versão

9,6
