---
permalink: api/reference_element_api_modifyvolume.html 
sidebar: sidebar 
keywords: volumes,volume,modifying,modify,change,changing,edit,editing,modifyvolume,settings 
summary: Você pode usar o método Modifyvolume para modificar as configurações em um volume existente. Você pode fazer modificações em um volume de cada vez e as alterações ocorrem imediatamente. 
---
= Modifyvolume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pode utilizar o `ModifyVolume` método para modificar as definições num volume existente. Você pode fazer modificações em um volume de cada vez e as alterações ocorrem imediatamente.

Se você não especificar valores de QoS ao modificar um volume, eles permanecerão os mesmos que antes da modificação. Você pode recuperar valores de QoS padrão para um volume recém-criado executando o `GetDefaultQoS` método.

Quando for necessário aumentar o tamanho de um volume que está sendo replicado, faça isso na seguinte ordem para evitar erros de replicação:

. Aumente o tamanho do volume com o acesso de replicationTarget.
. Aumente o tamanho da fonte ou do volume com o acesso readWrite.


Certifique-se de que os volumes de destino e de origem tenham o mesmo tamanho.


NOTE: Se você alterar o status de acesso para bloqueado ou replicationTarget, todas as conexões iSCSI existentes serão encerradas.



== Parâmetros

Este método tem os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
VolumeID
 a| 
O volumeID para o volume a ser modificado.
 a| 
número inteiro
 a| 
Nenhum
 a| 
Sim



 a| 
acesso
 a| 
Acesso permitido para o volume. Valores possíveis:

* `readOnly`: Só são permitidas operações de leitura.
* `readWrite`: Leituras e gravações são permitidas.
* `locked`: Não são permitidas leituras ou gravações. Se não for especificado, o valor de acesso não muda.
* `replicationTarget`: Identificar um volume como o volume alvo para um conjunto de volumes emparelhado. Se o volume não estiver emparelhado, o estado de acesso é bloqueado. Se um valor não for especificado, o valor de acesso não será alterado.
* `snapMirrorTarget`: Identificar um volume como o volume de destino para replicação do SnapMirror.

 a| 
cadeia de carateres
 a| 
Nenhum
 a| 
Não



 a| 
ID Contabilística
 a| 
O AccountID ao qual o volume é reatribuído. Se nenhum for especificado, o nome da conta anterior será usado.
 a| 
número inteiro
 a| 
Nenhum
 a| 
Não



 a| 
AssociateWithQoSPolicy
 a| 
Associe o volume à política de QoS especificada. Valores possíveis:

* `true`: Associe o volume à política de QoS especificada no parâmetro QoSPolicyID.
* `false`: Não associe o volume à política de QoS especificada no parâmetro QoSPolicyID. Quando falsa, qualquer associação de política existente é removida, independentemente de você especificar uma política de QoS no parâmetro QoSPolicy.

 a| 
booleano
 a| 
Nenhum
 a| 
Não



 a| 
atributos
 a| 
Lista de pares nome-valor no formato de objeto JSON.
 a| 
Objeto JSON
 a| 
Nenhum
 a| 
Não



 a| 
CreateTime
 a| 
Uma string de data ISO 8601 para definir como a nova data de criação de volume. Necessário se setCreateTime estiver definido como true.
 a| 
ISO 8601 string
 a| 
Nenhum
 a| 
Não



 a| 
EnableSnapMirrorReplication
 a| 
Determina se o volume pode ser usado para replicação com endpoints SnapMirror. Valores possíveis:

* `true`
* `false`

 a| 
booleano
 a| 
falso
 a| 
Não



| FifoSize | Especifica o número máximo de instantâneos First-in-First-out (FIFO) suportados pelo volume. Observe que os snapshots FIFO e não FIFO usam o mesmo pool de slots de snapshot disponíveis em um volume. Use esta opção para limitar o consumo de snapshot FIFO dos slots de snapshot disponíveis. Note que não é possível modificar este valor para ser inferior à contagem de instantâneos FIFO atual. | número inteiro | Nenhum | Não 


| MinFifoSize | Especifica o número de slots de snapshot que são reservados apenas para snapshots First-in-First-out (FIFO). Como os snapshots FIFO e não FIFO compartilham o mesmo pool, o parâmetro minFfoSize reduz o número total de possíveis snapshots não FIFO pela mesma quantidade. Observe que você não pode modificar esse valor para que ele fique em conflito com a contagem de instantâneos não FIFO atual. | número inteiro | Nenhum | Não 


 a| 
modo
 a| 
Modo de replicação de volume. Valores possíveis:

* `asynch`: Aguarda que o sistema reconheça que os dados são armazenados na fonte antes de gravar no destino.
* `sync`: Não espera que a confirmação da transmissão de dados da origem comece a gravar dados no destino.

 a| 
cadeia de carateres
 a| 
Nenhum
 a| 
Não



 a| 
qos
 a| 
As novas definições de qualidade de serviço para este volume. Se não for especificado, as definições de QoS não são alteradas. Valores possíveis:

* `minIOPS`
* `maxIOPS`
* `burstIOPS`

 a| 
xref:reference_element_api_qos.adoc[QoS]
 a| 
Nenhum
 a| 
Não



 a| 
QosPolicyID
 a| 
O ID da diretiva cujas configurações de QoS devem ser aplicadas aos volumes especificados. Este parâmetro é mutuamente exclusivo com o parâmetro qos.
 a| 
número inteiro
 a| 
Nenhum
 a| 
Não



 a| 
SetCreateTime
 a| 
Defina como True (verdadeiro) para alterar a data gravada da criação do volume.
 a| 
booleano
 a| 
Nenhum
 a| 
Não



 a| 
Totalizar tamanho
 a| 
O novo tamanho do volume em bytes. 1000000000 é igual a 1GB. O tamanho é arredondado para cima até o megabyte mais próximo em tamanho. Este parâmetro só pode ser utilizado para aumentar o tamanho de um volume.
 a| 
número inteiro
 a| 
Nenhum
 a| 
Não

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
volume
 a| 
Objeto contendo informações sobre o volume recém-modificado.
 a| 
xref:reference_element_api_volume.adoc[volume]

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "ModifyVolume",
  "params": {
     "volumeID": 5,
     "attributes": {
        "name1": "value1",
        "name2": "value2",
        "name3": "value3"
     },
     "qos": {
        "minIOPS": 60,
        "maxIOPS": 100,
        "burstIOPS": 150,
        "burstTime": 60
     },
      "access" :"readWrite"
     },
      "totalSize": 20000000000,
     "id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
  "id": 1,
  "result": {
      "volume": {
          "access": "readWrite",
          "accountID": 1,
          "attributes": {
              "name1": "value1",
              "name2": "value2",
              "name3": "value3"
          },
          "blockSize": 4096,
          "createTime": "2016-03-28T16:16:13Z",
          "deleteTime": "",
          "enable512e": true,
          "iqn": "iqn.2010-01.com.solidfire:jyay.1459181777648.5",
          "name": "1459181777648",
          "purgeTime": "",
          "qos": {
              "burstIOPS": 150,
              "burstTime": 60,
              "curve": {
                  "4096": 100,
                  "8192": 160,
                  "16384": 270,
                  "32768": 500,
                  "65536": 1000,
                  "131072": 1950,
                  "262144": 3900,
                  "524288": 7600,
                  "1048576": 15000
              },
              "maxIOPS": 100,
              "minIOPS": 60
          },
          "scsiEUIDeviceID": "6a79617900000005f47acc0100000000",
          "scsiNAADeviceID": "6f47acc1000000006a79617900000005",
          "sliceCount": 1,
          "status": "active",
          "totalSize": 1000341504,
          "virtualVolumeID": null,
          "volumeAccessGroups": [
              1
          ],
          "volumeID": 5,
          "volumePairs": []
      }
  }
}
----


== Novo desde a versão

9,6



== Encontre mais informações

xref:reference_element_api_getdefaultqos.adoc[GetDefaultQoS]
