---
permalink: api/reference_element_api_getnodehardwareinfo.html 
sidebar: sidebar 
keywords: node,hardware,info,get,getting,getnodehardwareinfo 
summary: Você pode usar o método GetNodeHardwareInfo para retornar todas as informações de hardware e status para o nó especificado. Isso geralmente inclui fabricantes, fornecedores, versões e outras informações de identificação de hardware associadas. 
---
= GetNodeHardwareInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `GetNodeHardwareInfo` método para retornar todas as informações e status de hardware para o nó especificado. Isso geralmente inclui fabricantes, fornecedores, versões e outras informações de identificação de hardware associadas.



== Parâmetro

Este método tem o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
NodeID
 a| 
A ID do nó para o qual as informações de hardware estão sendo solicitadas. As informações sobre um nó Fibre Channel são retornadas se um nó Fibre Channel for especificado.
 a| 
número inteiro
 a| 
Nenhum
 a| 
Sim

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
NodeHardwareInfo
 a| 
Informações de hardware para o nodeID especificado. Cada objeto nesta saída é rotulado com o nodeID do nó dado.
 a| 
xref:reference_element_api_hardwareinfo.adoc[HardwareInfo]

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "GetNodeHardwareInfo",
   "params": {
     "nodeID": 1
   },
"id" : 1
}
----


== Exemplo de resposta

Devido ao tamanho deste exemplo de resposta, ele está documentado em um tópico suplementar.



== Novo desde a versão

9,6



== Encontre mais informações

xref:reference_element_api_response_example_getnodehardwareinfo_fibre_channel.adoc[GetNodeHardwareInfo (saída para nós Fibre Channel)]

xref:reference_element_api_response_example_getnodehardwareinfo.adoc[GetNodeHardwareInfo (saída para iSCSI)]
