---
permalink: api/reference_element_api_getremotelogginghosts.html 
sidebar: sidebar 
keywords: remote,logging,hosts,host,get,getting,getremotelogginghosts 
summary: Você pode usar o método GetRemoteLoggingHosts para obter a lista atual de servidores de log. 
---
= GetRemoteLoggingHosts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `GetRemoteLoggingHosts` método para obter a lista atual de servidores de log.



[[parameters]]
== Parâmetros

Não existem parâmetros de entrada para `GetRemoteLoggingHosts` .



[[return-value]]
== Valor de retorno

O `GetRemoteLoggingHosts` O método tem o seguinte valor de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
RemoteHosts
 a| 
Lista o endereço IP, o FQDN e as informações de porta dos hosts configurados para receber informações de registro encaminhadas.
 a| 
xref:reference_element_api_loggingserver.adoc[Servidor de loggingServer] array

|===


[[request-example]]
== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "id": 3386609,
   "method": "GetRemoteLoggingHosts",
   "params": {}
}
----


[[response-example]]
== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
   "id": 3386609,
   "result": {
      "remoteHosts": [
         {
           "host": "172.16.1.20",
           "port": 10514
         },
         {
           "host": "172.16.1.25"
         },
         {
            "host": "syslogs.lab.company.net",
            "port": 514
         }
      ]
   }
}
----


[[new-since-version]]
== Novo desde a versão

Disponível a partir do ONTAP 9.6.



[[find-more-information]]
== Encontre mais informações

xref:reference_element_api_setremotelogginghosts.adoc[SetRemoteLoggingHosts]
