---
permalink: api/reference_element_api_listinitiators.html 
sidebar: sidebar 
keywords: initiators,initiator,list,listing,listinitiators,iqn,wwpn,iqns,wwpns 
summary: Você pode usar o método ListInitiators para obter a lista de IQNs do iniciador ou nomes de portas mundiais. 
---
= ListInitiators
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ListInitiators` método para obter a lista de IQNs do iniciador ou WWPNs (World Wide Port Names).



== Parâmetros

Este método tem os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
iniciadores
 a| 
Uma lista de IDs de iniciador a recuperar. Você pode fornecer este parâmetro ou o parâmetro startInitiatorID, mas não ambos.
 a| 
array inteiro
 a| 
Nenhum
 a| 
Não



 a| 
StartInitiatorID
 a| 
O ID do iniciador no qual iniciar a listagem. Você pode fornecer este parâmetro ou o parâmetro de iniciadores, mas não ambos.
 a| 
número inteiro
 a| 
0
 a| 
Não



 a| 
limite
 a| 
O número máximo de objetos do iniciador a serem retornados.
 a| 
número inteiro
 a| 
(ilimitado)
 a| 
Não

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
iniciadores
 a| 
Lista das informações do iniciador.
 a| 
xref:reference_element_api_initiator.adoc[iniciador] array

|===


== Exceções

Este método pode ter a seguinte exceção:

|===


| Nome | Descrição 


 a| 
XInvalidParameter
 a| 
Lançado se você incluir tanto os parâmetros startInitiatorID quanto os iniciadores na mesma chamada de método.

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "ListInitiators",
   "params": {},
   "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
  "id": 1,
  "result": {
    "initiators": [
      {
        "alias": "",
        "attributes": {},
        "initiatorID": 2,
        "initiatorName": "iqn.1993-08.org.debian:01:c84ffd71216",
        "volumeAccessGroups": [
          1
        ]
      }
    ]
  }
}
----


== Novo desde a versão

9,6
