---
permalink: api/reference_element_api_addvolumestovolumeaccessgroup.html 
sidebar: sidebar 
keywords: volume,volumes,adding,add,access,group,addvolumestovolumeaccessgroup 
summary: Você pode usar o método AddVolumesToVolumeAccessGroup para adicionar volumes a um grupo de acesso de volume especificado. 
---
= AddVolumesToVolumeAccessGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `AddVolumesToVolumeAccessGroup` método para adicionar volumes a um grupo de acesso de volume especificado.



== Parâmetros

Este método tem os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
volumes
 a| 
Lista de volumeIDs a serem adicionados ao grupo de acesso ao volume.
 a| 
array inteiro
 a| 
Nenhum
 a| 
Sim



 a| 
VolumeAccessGroupID
 a| 
VolumeAccessGroupID do grupo de acesso ao volume ao qual os volumes são adicionados.
 a| 
número inteiro
 a| 
Nenhum
 a| 
Sim

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
VolumeAccessGroup
 a| 
Um objeto contendo informações sobre o grupo de acesso de volume recém-modificado.
 a| 
xref:reference_element_api_volumeaccessgroup.adoc[VolumeAccessGroup]

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "AddVolumesToVolumeAccessGroup",
   "params": {
      "volumeAccessGroupID": 96,
      "volumes": [1,2]
   },
   "id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
  "id": 1,
  "result": {
    "volumeAccessGroup": {
      "attributes": {},
      "deletedVolumes": [
        346
      ],
      "initiatorIDs": [
        116,
        117
      ],
      "initiators": [
        "iqn.1993-08.org.debian:01:181324777",
        "iqn.1993-08.org.debian:01:181324888"
      ],
      "name": "northbanktest",
      "volumeAccessGroupID": 96,
      "volumes": [
        1,
        2
      ]
    }
  }
}
----


== Novo desde a versão

9,6
