---
permalink: api/reference_element_api_modifybackuptarget.html 
sidebar: sidebar 
keywords: modify,modifying,edit,editing,change,changing,backup,target,modifybackuptarget 
summary: Você pode usar o método ModifyBackupTarget para alterar os atributos de um destino de backup. 
---
= ModifyBackupTarget
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ModifyBackupTarget` método para alterar os atributos de um destino de backup.



== Parâmetros

Este método tem os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
BackupTargetID
 a| 
ID de destino exclusivo para o alvo modificar.
 a| 
número inteiro
 a| 
Nenhum
 a| 
Sim



 a| 
atributos
 a| 
Lista de pares nome-valor no formato de objeto JSON.
 a| 
Objeto JSON
 a| 
Nenhum
 a| 
Não



 a| 
nome
 a| 
Novo nome para o destino da cópia de segurança.
 a| 
cadeia de carateres
 a| 
Nenhum
 a| 
Não

|===


== Valores de retorno

Este método não tem valores de retorno.



== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "ModifyBackupTarget",
   "params": {
      "backupTargetID" : 1,
      "name": "yourtargetS3"
      "attributes" : {
          "size" : 500,
      }
   },
  "id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
   "id": 1,
   "result": {}
}
----


== Novo desde a versão

9,6
