---
permalink: api/reference_element_api_listclusteradmins.html 
sidebar: sidebar 
keywords: admin,admins,cluster,list,listing,listclusteradmins 
summary: Você pode usar o método ListClusterAdmins para retornar a lista de todos os administradores de cluster para o cluster. 
---
= ListClusterAdmins
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ListClusterAdmins` método para retornar a lista de todos os administradores de cluster do cluster.

Pode haver várias contas de administrador de cluster com diferentes níveis de permissões. Só pode existir um administrador de cluster principal no sistema. O administrador do cluster principal é o administrador que foi criado quando o cluster foi criado. Os administradores LDAP também podem ser criados ao configurar um sistema LDAP no cluster.



== Parâmetros

Este método tem o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
Mostrar Oculto
 a| 
Mostra usuários de administrador de cluster ocultos, como admin SNMP.
 a| 
booleano
 a| 
Nenhum
 a| 
Não

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
ClusterAdmins
 a| 
Informações sobre todos os administradores de cluster e LDAP que existem para um cluster.
 a| 
xref:reference_element_api_clusteradmin.adoc[Administrador exclusivo] array

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "ListClusterAdmins",
   "params": {},
    "showHidden": true
   "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
"id":1,
"result":{
  "clusterAdmins":[
     {
       "access":[
           "administrator"
       ],
       "attributes":null,
       "authMethod":"Cluster",
       "clusterAdminID":1,
       "username":"admin"
   },
   {
       "access":[
           "read",
           "administrator"
       ],
       "attributes":{
       },
       "authMethod":"Ldap",
       "clusterAdminID":7,
       "username":"john.smith"
   },
   {
       "access":[
           "read",
           "administrator"
       ],
       "attributes":{},
       "authMethod":"Ldap",
       "clusterAdminID":6,
       "username":"cn=admin1 jones,ou=ptusers,c=prodtest,dc=solidfire,dc=net"
       }
     ]
   }
}
----


== Novo desde a versão

9,6
