---
permalink: api/reference_element_api_getdrivehardwareinfo.html 
sidebar: sidebar 
keywords: drive,get,getting,hardware,info,getdrivehardwareinfo 
summary: Você pode usar o método GetDriveHardwareInfo para obter todas as informações de hardware para a unidade dada. Isso geralmente inclui fabricantes, fornecedores, versões e outras informações de identificação de hardware associadas. 
---
= GetDriveHardwareInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `GetDriveHardwareInfo` método para obter todas as informações de hardware para a unidade dada. Isso geralmente inclui fabricantes, fornecedores, versões e outras informações de identificação de hardware associadas.



== Parâmetro

Este método tem o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
ID de acesso
 a| 
ID da unidade para a solicitação.
 a| 
número inteiro
 a| 
Nenhum
 a| 
Sim

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
resultado
 a| 
Informações de hardware devolvidas para o ID de acesso especificado.
 a| 
xref:reference_element_api_hardwareinfo.adoc[HardwareInfo]

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "GetDriveHardwareInfo",
   "params": {
     "driveID": 5
   },
   "id" : 100
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
   "id" : 100,
   "result" : {
     "driveHardwareInfo" : {
       "description" : "ATA Drive",
       "dev" : "8:80",
       "devpath" : "/devices/pci0000:40/0000:40:01.0/0000:41:00.0/host6/port-6:0/expander-6:0/port-6:0:4/end_device-6:0:4/target6:0:4/6:0:4:0/block/sdf",
       "driveSecurityAtMaximum" : false,
       "driveSecurityFrozen" : false
       "driveSecurityLocked" : false,
       "logicalname" : "/dev/sdf",
       "product" : "INTEL SSDSA2CW300G3",
       "securityFeatureEnabled" : false,
       "securityFeatureSupported" : true,
       "serial" : "CVPR121400NT300EGN",
       "size" : "300069052416",
       "uuid" : "7e1fd5b9-5acc-8991-e2ac-c48f813a3884",
       "version" : "4PC10362"
     }
   }
}
----


== Novo desde a versão

9,6



== Encontre mais informações

xref:reference_element_api_listdrives.adoc[ListDrives]
