---
permalink: api/reference_element_api_getsnapmirrorclusteridentity.html 
sidebar: sidebar 
keywords: get,getting,SnapMirror,cluster,identity,GetSnapMirrorClusterIdentity 
summary: A IU da Web do software Element usa GetSnapMirrorClusterIdentity para obter informações de identidade sobre o cluster ONTAP. 
---
= GetSnapMirrorClusterIdentity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A IU da Web do software Element usa `GetSnapMirrorClusterIdentity` para obter informações de identidade sobre o cluster ONTAP.



== Parâmetro

Este método tem o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
SnapMirrorEndpointID
 a| 
Se fornecido, o sistema lista a identidade do cluster do endpoint com o snapMirrorEndpointID especificado. Se não for fornecido, o sistema lista a identidade do cluster de todos os endpoints SnapMirror conhecidos.
 a| 
número inteiro
 a| 
Nenhum
 a| 
Não

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
SnapMirrorClusterIdentity
 a| 
Uma lista de identidades de cluster de endpoints do SnapMirror.
 a| 
xref:reference_element_api_snapmirrorclusteridentity.adoc[SnapMirrorClusterIdentity] array

|===


== Novo desde a versão

10,1
