---
permalink: api/reference_element_api_getnodeactivetlsciphers.html 
sidebar: sidebar 
keywords: tls,cipher,ciphers,get,getting,getnodeactivetlsciphers,accepted 
summary: Você pode usar o método GetNodeActiveTlsCiphers em um único nó para obter uma lista das cifras TLS que são aceitas atualmente neste nó. Você pode usar esse método em nós de gerenciamento e storage. 
---
= GetNodeActiveTlsCiphers
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `GetNodeActiveTlsCiphers` método em um único nó para obter uma lista das cifras TLS que são aceitas atualmente neste nó. Você pode usar esse método em nós de gerenciamento e storage.



== Parâmetro

Este método não tem parâmetros de entrada.



== Valores de retorno

Este método tem os seguintes valores de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
MandatoryCiphers
 a| 
Lista de conjuntos de codificação TLS obrigatórios para o nó. São cifras que estão sempre ativas no nó.
 a| 
cadeia de carateres



 a| 
SuplementalCiphers
 a| 
Lista de conjuntos de codificação TLS suplementares para o nó.
 a| 
cadeia de carateres

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "GetNodeActiveTlsCiphers",
  "params": {},
  "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
      "id" : 1,
      "result" : {
        "mandatoryCiphers": [
            "DHE-RSA-AES256-SHA256",
            "DHE-RSA-AES256-GCM-SHA384",
            "ECDHE-RSA-AES256-SHA384",
            "ECDHE-RSA-AES256-GCM-SHA384"
        ],
        "supplementalCiphers": [
            "DHE-RSA-AES128-SHA256",
            "DHE-RSA-AES128-GCM-SHA256",
            "ECDHE-RSA-AES128-SHA256",
            "ECDHE-RSA-AES128-GCM-SHA256"
        ]
    }
}
----