---
permalink: api/reference_element_api_getfeaturestatus.html 
sidebar: sidebar 
keywords: feature,status,cluster,get,getting,getfeaturestatus 
summary: Você pode usar o método GetFeatureStatus para recuperar o status de um recurso de cluster. 
---
= GetFeatureStatus
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `GetFeatureStatus` método para recuperar o status de um recurso de cluster.



== Parâmetro

Este método tem o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
recurso
 a| 
O status de um recurso de cluster. Se nenhum valor for fornecido, o sistema retornará um status de todos os recursos. Valores possíveis:

* Vvols: Recuperar status para o recurso de cluster do VVols.
* SnapMirror: Recuperar o status do recurso de cluster de replicação do SnapMirror.
* FIPS: Recuperar o status do recurso de criptografia FIPS 140-2 para comunicação HTTPS.
* FipsDrives: Recupere o status do recurso de criptografia da unidade FIPS 140-2.

 a| 
cadeia de carateres
 a| 
Nenhum
 a| 
Não

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
caraterísticas
 a| 
Um array de objetos de recurso indicando o nome do recurso e seu status. Membros do objeto:

* Característica: (String) o nome do recurso.
* Ativado: (booleano) se o recurso está ativado ou não.

 a| 
Array de objetos JSON

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "GetFeatureStatus",
    "params": {
    },
    "id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
    "id": 1,
    "result": {
        "features": [
            {
                "enabled": true,
                "feature": "Vvols"
            },
            {
                "enabled": true,
                "feature": "SnapMirror"
            },
            {
                "enabled": true,
                "feature": "Fips"
            },
            {
                "enabled": true,
                "feature": "FipsDrives"
            }
        ]
    }
}
----


== Novo desde a versão

9,6
