---
permalink: api/reference_element_api_getpatchinfo.html 
sidebar: sidebar 
keywords: get,patch,info,patches,getpatchinfo 
summary: Você pode usar o método GetPatchInfo para obter informações sobre patches instalados em um nó. 
---
= GetPatchInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `GetPatchInfo` método para obter informações sobre os patches do software Element instalados em um nó de storage.



== Parâmetros

Este método tem os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


| `force`  a| 
Forçar a execução do método em todos os nós no cluster de storage. Você só precisa disso quando você emite a API para um endereço IP de cluster em vez de um único nó. Valores possíveis:

* `true`
* `false`

| booleano | `false` | Não 
|===


== Valores de retorno

Este método tem os seguintes valores de retorno:

|===
| Nome | Descrição | Tipo 


| patches | Objeto contendo informações sobre os patches instalados neste nó. | Objeto JSON 
|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "GetPatchInfo",
   "params": {
      "force": false,
      },
   "id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
    "id": 1,
    "result": {
        "patches": {
          "SUST936": {
          "date": "Wed 09 Dec 2020 10:41:59 PM UTC",
          "description": "BMC fixes",
          "newFiles": [
              "None"
          ],
          "patchedFiles": [
              "Patched_file_1.bin",
              "Patched_file_2.dat",
              "Patched_file_3.tgz"
          ]
          }
        }
    }
}

----


== Novo desde a versão

12,3
