---
permalink: api/reference_element_api_modifystoragecontainer.html 
sidebar: sidebar 
keywords: virtual,volume,storage,container,vvol,modify,modifying,change,changing,edit,editing 
summary: Você pode usar o método ModifyStorageContainer para fazer alterações em um recipiente de armazenamento de volume virtual existente. 
---
= ModifyStorageContainer
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ModifyStorageContainer` método para fazer alterações em um recipiente de armazenamento de volume virtual existente.



== Parâmetros

Este método tem os seguintes parâmetros de entrada:

|===


| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
StorageContainerID
 a| 
O ID exclusivo do contentor de armazenamento de volume virtual a ser modificado.
 a| 
UUID
 a| 
Nenhum
 a| 
Sim



 a| 
InitiatorSecret
 a| 
O novo segredo para autenticação CHAP para o iniciador.
 a| 
cadeia de carateres
 a| 
Nenhum
 a| 
Não



 a| 
TargetSecret
 a| 
O novo segredo para autenticação CHAP para o destino.
 a| 
cadeia de carateres
 a| 
Nenhum
 a| 
Não

|===


== Valores de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
StorageContainer
 a| 
Informações sobre o contentor de armazenamento recém-criado.
 a| 
xref:reference_element_api_storagecontainer.adoc[StorageContainer]

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "ModifyStorageContainer",
    "params": {
      "storageContainerID": "6c95e24f-9f0b-4793-affb-5a4bc6c3d7e1",
      "targetSecret": "O,IM;tOQdn9$JJ*8"
    },
    "id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
  "id": 1,
  "result": {
    "storageContainer": {
      "accountID": 8,
      "initiatorSecret": "T$|5TO>2IY5sk4@k",
      "name": "doctest1",
      "protocolEndpointType": "SCSI",
      "status": "active",
      "storageContainerID": "6c95e24f-9f0b-4793-affb-5a4bc6c3d7e1",
      "targetSecret": "O,IM;tOQdn9$JJ*8"
    }
  }
}
----


== Novo desde a versão

9,6
