---
permalink: api/reference_element_api_enablebmccoldreset.html 
sidebar: sidebar 
keywords: BMC cold reset,BMC reset,enable BMC 
summary: 'Você pode usar o método EnableBmcColdReset para habilitar uma tarefa em segundo plano que redefine periodicamente o controlador de gerenciamento de placa base (BMC) para todos os nós no cluster.' 
---
= EnableBmcColdReset
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `EnableBmcColdReset` método para habilitar uma tarefa em segundo plano que redefine periodicamente o controlador de gerenciamento da placa base (BMC) para todos os nós do cluster.



== Parâmetro

Este método tem o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
tempo limite
 a| 
O tempo entre as operações de reinicialização do BMC, em minutos.
 a| 
número inteiro
 a| 
20160 minutos
 a| 
Não

|===


== Valores de retorno

Este método tem o seguinte valor de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
CBmcResetDurationMinutes
 a| 
Retorna o tempo entre intervalos de reinicialização. O intervalo deve ser sempre 0 após a conclusão do comando.
 a| 
número inteiro

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
    "method": "EnableBmcColdReset",
    "params": {
                "timeout": 36000
    },
    "id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
    "id": 1,
    "result": {
        "cBmcResetDurationMinutes": 36000
    }
}
----


== Novo desde a versão

12,0
