---
permalink: api/reference_element_api_completevolumepairing.html 
sidebar: sidebar 
keywords: volume,pairing,CompleteVolumePairing,pair,volumes,complete,completing 
summary: Pode utilizar CompleteVolumePairing para concluir o emparelhamento de dois volumes. 
---
= CompleteVolumePairing
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pode utilizar `CompleteVolumePairing` para concluir o emparelhamento de dois volumes.



== Parâmetros

Este método tem os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
VolumeID
 a| 
O ID do volume que irá completar o par de volumes.
 a| 
número inteiro
 a| 
Nenhum
 a| 
Sim



 a| 
VolumePairingKey
 a| 
A chave retornada do xref:reference_element_api_startvolumepairing.adoc[StartVolumePairing]método API.
 a| 
cadeia de carateres
 a| 
Nenhum
 a| 
Sim

|===


== Valor de retorno

Este método não tem valores de retorno.



== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "CompleteVolumePairing",
   "params": {
        "volumeID" : 12,
        "volumePairingKey" : "7b22636c7573746572506169724944223a312c22636c75737465725061697255554944223a2231636561313336322d346338662d343631612d626537322d373435363661393533643266222c22636c7573746572556e697175654944223a2278736d36222c226d766970223a223139322e3136382e3133392e313232222c226e616d65223a224175746f54657374322d63307552222c2270617373776f7264223a22695e59686f20492d64774d7d4c67614b222c22727063436f6e6e656374696f6e4944223a3931333134323634392c22757365726e616d65223a225f5f53465f706169725f50597a796647704c7246564432444a42227d"
        },
   "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
"id": 1,
"result": {}
}
----


== Novo desde a versão

9,6



== Encontre mais informações

xref:reference_element_api_startvolumepairing.adoc[StartVolumePairing]
