---
permalink: api/reference_element_api_createbackuptarget.html 
sidebar: sidebar 
keywords: create,creating,backup,target,CreateBackupTarget 
summary: Você pode usar o CreateBackupTarget para criar e armazenar informações de destino de backup para que você não precise inseri-las novamente cada vez que um backup é criado. 
---
= CreateBackupTarget
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar `CreateBackupTarget` para criar e armazenar informações de destino de backup para que você não precise inseri-las novamente cada vez que um backup é criado.



== Parâmetros

Este método tem os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
nome
 a| 
Nome para o destino da cópia de segurança.
 a| 
cadeia de carateres
 a| 
Nenhum
 a| 
Sim



 a| 
atributos
 a| 
Lista de pares nome-valor no formato de objeto JSON.
 a| 
Objeto JSON
 a| 
Nenhum
 a| 
Sim (mas pode estar vazio)

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
BackupTargetID
 a| 
Identificador exclusivo atribuído ao novo destino de cópia de segurança.
 a| 
número inteiro

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "CreateBackupTarget",
   "params": {
      "name": "mytargetbackup"
   },
"id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
   "id": 1,
   "result": {
      "backupTargetID": 1
   }
}
----


== Novo desde a versão

9,6
