---
permalink: api/reference_element_api_removeaccount.html 
sidebar: sidebar 
keywords: account,accounts,remove,removing,deleting,delete,purge,volume,volumes,removeaccount 
summary: Você pode usar o método RemoveAccount para remover uma conta existente. Você deve excluir e limpar todos os volumes associados à conta usando Deletevolume antes de remover a conta. Se os volumes na conta ainda estiverem pendentes de exclusão, você não poderá usar o RemoveAccount para remover a conta. 
---
= Contagem remota
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `RemoveAccount` método para remover uma conta existente. Você deve excluir e limpar todos os volumes associados à conta usando `DeleteVolume` antes de remover a conta. Se os volumes na conta ainda estiverem pendentes de exclusão, você não poderá usar `RemoveAccount` para remover a conta.



[[parameter]]
== Parâmetro

Este método tem o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
ID Contabilística
 a| 
O ID da conta a ser removida.
 a| 
número inteiro
 a| 
Nenhum
 a| 
Sim

|===


[[return-value]]
== Valor de retorno

Este método não tem valor de retorno.



[[request-example]]
== Exemplo de solicitação

As solicitações para este método são semelhantes ao exemplo a seguir.

[listing]
----
{
   "method": "RemoveAccount",
   "params": {
     "accountID"  : 25
   },
   "id" : 1
}
----


[[response-example]]
== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----

{
 "id" : 1,
 "result" : { }
}
----


[[new-since-version]]
== Novo desde a versão

9,6



[[find-more-information]]
== Encontre mais informações

xref:reference_element_api_deletevolume.adoc[Deletevolume]
