---
permalink: api/reference_element_api_deletestoragecontainers.html 
sidebar: sidebar 
keywords: virtual,volume,storage,container,delete,deleting,vvol,DeleteStorageContainers 
summary: 'Você pode usar o método DeleteStorageContainers para remover até 2000 contentores de armazenamento de volume Virtual (VVol) do sistema ao mesmo tempo. Os contêineres de storage removidos não devem conter vols.' 
---
= Delegados do StorageContainers
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `DeleteStorageContainers` método para remover até 2000 contêineres de storage de volume virtual (VVol) do sistema ao mesmo tempo. Os contêineres de storage removidos não devem conter vols.



== Parâmetros

Este método tem o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
StorageContainerIDs
 a| 
Uma lista de IDs dos contentores de armazenamento a eliminar. Pode especificar até 2000 IDs na lista.
 a| 
Array UUUID
 a| 
Nenhum
 a| 
Sim

|===


== Valores de retorno

Este método não tem valores de retorno.



== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "DeleteStorageContainers",
    "params": {
        "storageContainerIDs" : ["a9ec1138-e386-4a44-90d7-b9acbbc05176"]
    },
    "id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
  "id": 1,
  "result": {}
}
----


== Novo desde a versão

9,6
