---
permalink: api/reference_element_api_listvolumeqoshistograms.html 
sidebar: sidebar 
keywords: qos,usage,volume,histogram,generate,listvolumeqoshistograms,histograms 
summary: Você pode usar o método ListVolumeQoSHistogramas para gerar um histograma de uso de QoS de volume para um volume ou vários volumes. Isso permite que você entenda melhor como os volumes estão usando QoS. 
---
= ListVolumeQoSHistogramas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ListVolumeQoSHistograms` método para gerar um histograma de uso de QoS de volume para um volume ou vários volumes. Isso permite que você entenda melhor como os volumes estão usando QoS.



== Parâmetros

Este método tem os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
VolumeIDs
 a| 
Uma lista opcional de IDs de volume especificando quais volumes devem ter histogramas de QoS gerados.
 a| 
array inteiro
 a| 
Nenhum
 a| 
Não

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
QosHistogramas
 a| 
Uma lista de objetos que descrevem o uso de volume para um ou mais volumes.
 a| 
Array de objetos JSON

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
	"method": "ListVolumeQoSHistograms",
		"params": {
			"volumeIDs": [1]
		},
	"id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
	"id": 1,
	"result": {
		"qosHistograms": [
		{
			"histograms": {
			"belowMinIopsPercentages": {
				"Bucket1To19": 2406,
				"Bucket20To39": 3,
				"Bucket40To59": 0,
				"Bucket60To79": 4,
				"Bucket80To100": 0
			},
				"minToMaxIopsPercentages": {
				"Bucket101Plus": 0,
				"Bucket1To19": 0,
				"Bucket20To39": 0,
				"Bucket40To59": 2,
				"Bucket60To79": 0,
				"Bucket80To100": 0
			},
				"readBlockSizes": {
				"Bucket131072Plus": 0,
				"Bucket16384To32767": 0,
				"Bucket32768To65535": 0,
				"Bucket4096To8191": 0,
				"Bucket65536To131071": 0,
				"Bucket8192To16383": 0
			},
				"targetUtilizationPercentages": {
				"Bucket0": 134943,
				"Bucket101Plus": 0,
				"Bucket1To19": 2409,
				"Bucket20To39": 4,
				"Bucket40To59": 0,
				"Bucket60To79": 2,
				"Bucket80To100": 0
			},
				"throttlePercentages": {
				"Bucket0": 137358,
				"Bucket1To19": 0,
				"Bucket20To39": 0,
				"Bucket40To59": 0,
				"Bucket60To79": 0,
				"Bucket80To100": 0
			},
				"writeBlockSizes": {
				"Bucket131072Plus": 0,
				"Bucket16384To32767": 0,
				"Bucket32768To65535": 0,
				"Bucket4096To8191": 0,
				"Bucket65536To131071": 0,
				"Bucket8192To16383": 0
			}
		},
			"timestamp": "2018-06-21T18:45:52.010844Z",
			"volumeID": 1
		}
	]
}
}
----