---
permalink: api/reference_element_api_loggingserver.html 
sidebar: sidebar 
keywords: object,objects,loggingServer 
summary: O objeto logingServer contém informações sobre quaisquer hosts de log configurados para o cluster de armazenamento. Você pode usar GetRemoteLoggingHosts para determinar quais são os hosts de log atuais e, em seguida, usar SetRemoteLoggingHosts para definir a lista desejada de hosts de log atuais e novos. 
---
= Servidor de loggingServer
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O objeto loggingServer armazena informações sobre os hosts de registro configurados para o cluster de armazenamento.  Usar `GetRemoteLoggingHosts` para visualizar os hosts de registro atuais e, em seguida, usar `SetRemoteLoggingHosts` Para definir a lista desejada de hosts de registro atuais e novos.



== Membros do objeto

Este objeto contém os seguintes membros:

|===
| Nome | Descrição | Tipo 


 a| 
host
 a| 
FQDN ou endereço IP do servidor de logs
 a| 
cadeia de carateres



 a| 
porta
 a| 
Número da porta usada para comunicação com o servidor de logs.
 a| 
número inteiro

|===
.Informações relacionadas
* link:reference_element_api_getremotelogginghosts.html["GetRemoteLoggingHosts"]
* link:reference_element_api_setremotelogginghosts.html["SetRemoteLoggingHosts"]

