---
permalink: api/reference_element_api_getnetworkinterface.html 
sidebar: sidebar 
keywords: nodes,node,network,interface,get,getting,getnetworkinterface 
summary: Você pode usar o método GetNetworkInterface para obter informações sobre uma interface de rede em um nó. 
---
= GetNetworkInterface
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `GetNetworkInterface` método para obter informações sobre uma interface de rede em um nó.



== Parâmetros

Este método tem os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
interface
 a| 
O nome da interface para obter informações sobre cada nó. Valores possíveis:

* Bond1G
* Bond10G

 a| 
cadeia de carateres
 a| 
Nenhum
 a| 
Não



 a| 
força
 a| 
Defina este parâmetro como true para ser executado em todos os nós no cluster.
 a| 
booleano
 a| 
falso
 a| 
Não

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
nós
 a| 
Um array de objetos que descreve a interface para cada nó de storage no cluster de storage. Cada objeto dentro do array contém os seguintes itens:

* NodeID: (Inteiro) o ID do nó de armazenamento no cluster de armazenamento ao qual as informações da interface se aplicam.
* Resultado: (xref:reference_element_api_networkinterface.adoc[NetworkInterface]) Informações de configuração da interface para este nó de armazenamento.

 a| 
Array de objetos JSON

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
	"method": "GetNetworkInterface",
	"params": {
		"interface": "Bond1G",
		"force": true
		},
	"id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
	"id": 1,
	"result": {
		"nodes": [
			{
				"nodeID": 1,
				"result": {
					"interface": {
						"address": "10.117.64.32",
						"addressV6": "::",
						"broadcast": "10.117.79.255",
						"macAddress": "90:b1:1c:42:e0:1e",
						"mtu": 1500,
						"name": "Bond1G",
						"namespace": false,
						"netmask": "255.255.240.0",
						"status": "UpAndRunning",
						"type": "BondMaster",
						"virtualNetworkTag": 0
					}
				}
			},
			{
				"nodeID": 2,
				"result": {
					"interface": {
						"address": "10.117.64.35",
						"addressV6": "::",
						"broadcast": "10.117.79.255",
						"macAddress": "d4:ae:52:7a:ae:23",
						"mtu": 1500,
						"name": "Bond1G",
						"namespace": false,
						"netmask": "255.255.240.0",
						"status": "UpAndRunning",
						"type": "BondMaster",
						"virtualNetworkTag": 0
					}
				}
			},
			{
				"nodeID": 3,
				"result": {
					"interface": {
						"address": "10.117.64.39",
						"addressV6": "::",
						"broadcast": "10.117.79.255",
						"macAddress": "c8:1f:66:f0:9d:17",
						"mtu": 1500,
						"name": "Bond1G",
						"namespace": false,
						"netmask": "255.255.240.0",
						"status": "UpAndRunning",
						"type": "BondMaster",
						"virtualNetworkTag": 0
					}
				}
			},
			{
				"nodeID": 4,
				"result": {
					"interface": {
						"address": "10.117.64.107",
						"addressV6": "::",
						"broadcast": "10.117.79.255",
						"macAddress": "b8:ca:3a:f5:24:f8",
						"mtu": 1500,
						"name": "Bond1G",
						"namespace": false,
						"netmask": "255.255.240.0",
						"status": "UpAndRunning",
						"type": "BondMaster",
						"virtualNetworkTag": 0
					}
				}
			}
		]
	}
}
----


== Novo desde a versão

9,6
