---
permalink: api/reference_element_api_modifyvolumeaccessgroup.html 
sidebar: sidebar 
keywords: volume,access,group,modify,modifying,updating,changing,change,update,edit,editing,modifyvolumeaccessgroup 
summary: Você pode usar o método ModifyVolumeAccessGroup para atualizar iniciadores e adicionar ou remover volumes de um grupo de acesso de volume. 
---
= ModifyVolumeAccessGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ModifyVolumeAccessGroup` método para atualizar iniciadores e adicionar ou remover volumes de um grupo de acesso de volume.

Se um iniciador ou volume especificado for uma cópia do que existe atualmente, o grupo de acesso ao volume é deixado como está. Se você não especificar um valor para volumes ou iniciadores, a lista atual de iniciadores e volumes não será alterada.



== Parâmetros

Este método tem os seguintes parâmetros de entrada:

|===


| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
VolumeAccessGroupID
 a| 
A ID do grupo de acesso ao volume a modificar.
 a| 
número inteiro
 a| 
Nenhum
 a| 
Sim



 a| 
nome
 a| 
O novo nome para este grupo de acesso ao volume.
 a| 
cadeia de carateres
 a| 
Nenhum
 a| 
Não



 a| 
atributos
 a| 
Lista de pares nome-valor no formato de objeto JSON.
 a| 
Objeto JSON
 a| 
Nenhum
 a| 
Não



 a| 
iniciadores
 a| 
Lista de IDs ou nomes de iniciadores (IQNs e WWPNs) a incluir no grupo de acesso de volume. Se você passar uma lista de nomes de iniciadores, os iniciadores serão criados se eles ainda não existirem. Se você passar uma lista de IDs de iniciador, o método retornará um erro se algum dos iniciadores ainda não existir. Passar nomes de iniciador é obsoleto; você deve usar IDs de iniciador sempre que possível.
 a| 
array inteiro (recomendado) ou array de cadeia de carateres (obsoleto)
 a| 
Nenhum
 a| 
Não



 a| 
DeleteOrphanInitiators
 a| 
Especifica se os objetos do iniciador devem ser excluídos após serem removidos de um grupo de acesso de volume ou não. Valores possíveis:

* Verdadeiro: Excluir objetos do iniciador depois que eles são removidos de um grupo de acesso de volume.
* Falso: Não exclua objetos do iniciador depois que forem removidos de um grupo de acesso de volume. Este é o padrão.

 a| 
booleano
 a| 
falso
 a| 
Não



 a| 
volumes
 a| 
Uma lista de IDs de volume de volumes a modificar.
 a| 
array inteiro
 a| 
Nenhum
 a| 
xref:reference_element_api_volumeaccessgroup.adoc[VolumeAccessGroup]

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
VolumeAccessGroup
 a| 
Um objeto contendo informações sobre o grupo de acesso de volume recém-modificado.
 a| 
xref:reference_element_api_volumeaccessgroup.adoc[VolumeAccessGroup]

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "ModifyVolumeAccessGroup",
   "params": {
      "volumeAccessGroupID": 96,
      "name": "accessgrouptest",
      "initiators": [115,114],
      "volumes": [
         346
    ],
      "attributes": {}
   }
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
  "id": null,
  "result": {
    "volumeAccessGroup": {
      "attributes": {},
      "deletedVolumes": [
        327
      ],
      "initiatorIDs": [
        114,
        115
      ],
      "initiators": [
        "iqn.1998-01.com.vmware:desk1-esx1-577b283a",
        "iqn.1998-01.com.vmware:donesq-esx1-421b281b"
      ],
      "name": "accessgrouptest",
      "volumeAccessGroupID": 96,
      "volumes": [
        346
      ]
    }
  }
}
----


== Novo desde a versão

9,6



== Encontre mais informações

* xref:reference_element_api_addinitiatorstovolumeaccessgroup.adoc[AddInitiatorsToVolumeAccessGroup]
* xref:reference_element_api_addvolumestovolumeaccessgroup.adoc[AddVolumesToVolumeAccessGroup]
* xref:reference_element_api_removeinitiatorsfromvolumeaccessgroup.adoc[RemoveInitiatorsFromVolumeAccessGroup]
* xref:reference_element_api_removevolumesfromvolumeaccessgroup.adoc[RemoveVolumesFromVolumeAccessGroup]

