---
permalink: api/reference_element_api_resyncsnapmirrorrelationship.html 
sidebar: sidebar 
keywords: SnapMirror,relationship,resync,resyncing,ResyncSnapMirrorRelationship 
summary: A IU da Web do software Element usa o método ResyncSnapMirrorRelationship para estabelecer ou restabelecer uma relação de espelhamento entre um endpoint de origem e destino. Quando você ressincroniza uma relação, o sistema remove snapshots no volume de destino que são mais recentes do que a cópia snapshot comum e, em seguida, monta o volume de destino como um volume de proteção de dados com a cópia snapshot comum como a cópia snapshot exportada. 
---
= ResyncSnapMirrorRelacionship
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A IU da Web do software Element usa o `ResyncSnapMirrorRelationship` método para estabelecer ou restabelecer uma relação de espelhamento entre um endpoint de origem e destino. Quando você ressincroniza uma relação, o sistema remove snapshots no volume de destino que são mais recentes do que a cópia snapshot comum e, em seguida, monta o volume de destino como um volume de proteção de dados com a cópia snapshot comum como a cópia snapshot exportada.



== Parâmetros

Este método tem os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
SnapMirrorEndpointID
 a| 
O ID do ponto de extremidade do sistema de armazenamento ONTAP remoto que se comunica com o cluster de armazenamento Element.
 a| 
número inteiro
 a| 
Nenhum
 a| 
Sim



 a| 
Destinaçãovolume
 a| 
O volume de destino na relação SnapMirror.
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[SnapMirrorVolumeinfo]
 a| 
Nenhum
 a| 
Sim



 a| 
MaxTransferRate
 a| 
Especifica a taxa máxima de transferência de dados entre os volumes em kilobytes por segundo. O valor padrão, 0, é ilimitado e permite que o relacionamento SnapMirror utilize totalmente a largura de banda de rede disponível.
 a| 
número inteiro
 a| 
Nenhum
 a| 
Não



 a| 
Sourcevolume
 a| 
O volume de origem na relação SnapMirror.
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[SnapMirrorVolumeinfo]
 a| 
Nenhum
 a| 
Não

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
SnapMirrorRelacionship
 a| 
Um objeto contendo informações sobre a relação ressinced SnapMirror.
 a| 
xref:reference_element_api_snapmirrorrelationship.adoc[SnapMirrorRelacionship]

|===


== Novo desde a versão

10,1
