---
permalink: api/reference_element_api_startvolumepairing.html 
sidebar: sidebar 
keywords: volume,pair,pairing,start,starting,startvolumepairing 
summary: Pode utilizar o método StartVolumePairing para criar uma chave codificada a partir de um volume utilizado para emparelhar com outro volume. A chave que este método cria é utilizada no método CompleteVolumePairing para estabelecer um emparelhamento de volume. 
---
= StartVolumePairing
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `StartVolumePairing` método para criar uma chave codificada a partir de um volume que é usado para emparelhar com outro volume. A chave que este método cria é utilizada no `CompleteVolumePairing` método para estabelecer um emparelhamento de volume.



== Parâmetros

Este método tem os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
modo
 a| 
O modo do volume para iniciar o processo de emparelhamento. O modo só pode ser definido se o volume for o volume de origem. Valores possíveis:

* `Async`: As gravações são reconhecidas quando são concluídas localmente. O cluster não espera que as gravações sejam replicadas no cluster de destino. (Padrão se nenhum parâmetro de modo especificado.)
* `Sync`: A fonte reconhece a gravação quando os dados são armazenados localmente e no cluster remoto.
* `SnapshotsOnly`: Apenas os instantâneos criados no cluster de origem são replicados. As gravações ativas do volume de origem não são replicadas.

 a| 
cadeia de carateres
 a| 
Nenhum
 a| 
Não



 a| 
VolumeID
 a| 
A ID do volume no qual iniciar o processo de emparelhamento.
 a| 
número inteiro
 a| 
Nenhum
 a| 
Sim

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
VolumePairingKey
 a| 
Uma cadeia de carateres que é usada pelo xref:reference_element_api_completevolumepairing.adoc[CompleteVolumePairing] método API.
 a| 
cadeia de carateres

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "StartVolumePairing",
   "params": {
         "mode": "Async",
	 "volumeID" : 14
      },
   "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
   "id" : 1,
   "result" : {
      "volumePairingKey" : "7b226d766970223a223139322e3136382e3133392e313232222c22766f6c756d654944223a312c22766f6c756d654e616d65223a2254657374222c22766f6c756d655061697255554944223a2236393632346663622d323032652d343332352d613536392d656339633635356337623561227d"
      }
}
----


== Novo desde a versão

9,6



== Encontre mais informações

xref:reference_element_api_completevolumepairing.adoc[CompleteVolumePairing]
