---
permalink: api/reference_element_api_deleteclusterinterfacepreference.html 
sidebar: sidebar 
keywords: cluster,interface,preferences,delete,deleting,DeleteClusterInterfacePreference 
summary: O método DeleteClusterInterfacePreference permite que sistemas integrados com clusters de armazenamento que executam o software Element excluam uma preferência de interface de cluster existente. Este método é para uso interno. 
---
= DeleteClusterInterfacePreference
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
 `DeleteClusterInterfacePreference`O método permite que sistemas integrados a clusters de storage que executam o software Element excluam uma preferência de interface de cluster existente. Este método é para uso interno.



== Parâmetros

Este método tem o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
nome
 a| 
O nome da preferência da interface do cluster a ser excluída.
 a| 
cadeia de carateres
 a| 
Nenhum
 a| 
Sim

|===


== Valores de retorno

Este método não tem valor de retorno.



== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
	"method": "DeleteClusterInterfacePreference",
	"params": {
		"name": "prefname"
		},
	"id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
    "id": 1,
    "result": {}
}
----


== Novo desde a versão

11,0
