---
permalink: api/reference_element_api_getremotelogginghosts.html 
sidebar: sidebar 
keywords: remote,logging,hosts,host,get,getting,getremotelogginghosts 
summary: Você pode usar o método GetRemoteLoggingHosts para obter a lista atual de servidores de log. 
---
= GetRemoteLoggingHosts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `GetRemoteLoggingHosts` método para obter a lista atual de servidores de log.



== Parâmetros

Este método não tem parâmetros de entrada.



== Valor de retorno

Este método tem o seguinte valor de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
RemoteHosts
 a| 
Lista de endereço IP e informações de porta sobre hosts configurados para receber informações de Registro encaminhadas.
 a| 
xref:reference_element_api_loggingserver.adoc[Servidor de loggingServer] array

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "id": 3386609,
   "method": "GetRemoteLoggingHosts",
   "params": {}
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
   "id": 3386609,
   "result": {
      "remoteHosts": [
         {
           "host": "172.16.1.20",
           "port": 10514
         },
         {
           "host": "172.16.1.25"
         }
      ]
   }
}
----


== Novo desde a versão

9,6



== Encontre mais informações

xref:reference_element_api_setremotelogginghosts.adoc[SetRemoteLoggingHosts]
