---
permalink: api/reference_element_api_deleteauthsessionsbyclusteradmin.html 
sidebar: sidebar 
keywords: auth sessions,cluster,admin,delete,authentication sessions 
summary: Você pode usar o método DeleteAuthSessionsByClusterAdmin para excluir todas as sessões de autenticação associadas ao ClusterAdminID especificado. Se o ClusterAdminID especificado for mapeado para um grupo de usuários, todas as sessões de autenticação para todos os membros desse grupo serão excluídas. Para exibir uma lista de sessões para possível exclusão, use o método ListAuthSessionsByClusterAdmin com o parâmetro ClusterAdminID. 
---
= DeleteAuthSessionsByClusterAdmin
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `DeleteAuthSessionsByClusterAdmin` método para excluir todas as sessões de autenticação associadas ao `ClusterAdminID` especificado . Se o ClusterAdminID especificado for mapeado para um grupo de usuários, todas as sessões de autenticação para todos os membros desse grupo serão excluídas. Para exibir uma lista de sessões para possível exclusão, use o método ListAuthSessionsByClusterAdmin com o `ClusterAdminID` parâmetro.



== Parâmetros

Este método tem o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
ClausterAdminID
 a| 
Identificador exclusivo para o administrador do cluster.
 a| 
número inteiro
 a| 
Nenhum
 a| 
Sim

|===


== Valores de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
sessões
 a| 
Informações de sessão para as sessões de autenticação excluídas.
 a| 
link:reference_element_api_authsessioninfo.html["AuthSessionInfo"]

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "DeleteAuthSessionsByClusterAdmin",
  "params": {
    "clusterAdminID": 1
  }
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
"sessions": [
      {
        "accessGroupList": [
          "administrator"
        ],
        "authMethod": "Cluster",
        "clusterAdminIDs": [
          1
        ],
        "finalTimeout": "2020-03-14T19:21:24Z",
        "idpConfigVersion": 0,
        "lastAccessTimeout": "2020-03-11T19:51:24Z",
        "sessionCreationTime": "2020-03-11T19:21:24Z",
        "sessionID": "b12bfc64-f233-44df-8b9f-6fb6c011abf7",
        "username": "admin"
      }
    ]
}
----


== Novo desde a versão

12,0
