---
permalink: api/reference_element_api_protectionschemeresiliency.html 
sidebar: sidebar 
keywords: object,objects,protectionSchemeResiliency 
summary: 'O objeto protectionSchemeResiliency contém informações sobre se um cluster de armazenamento, para um esquema de proteção específico, pode se curar automaticamente de uma ou mais falhas em sua proteção associada DomainType. Um cluster de armazenamento é considerado curado quando ele pode continuar lendo e gravando dados por meio da falha de qualquer nó de armazenamento único (um estado conhecido como tolerância do nó).' 
---
= Proteção SchemeResiliency
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O objeto protectionSchemeResiliency contém informações sobre se um cluster de armazenamento, para um esquema de proteção específico, pode se curar automaticamente de uma ou mais falhas em sua proteção associada DomainType. Um cluster de storage é considerado curado quando pode continuar lendo e gravando dados por meio da falha de qualquer nó de storage único (um estado conhecido como tolerância do nó).



== Membros do objeto

Este objeto contém os seguintes membros:

|===
| Nome | Descrição | Tipo 


 a| 
ProtecçãoScheme
 a| 
O esquema de proteção atual desse cluster de storage. O único valor possível é doubleHelix.
 a| 
cadeia de carateres



 a| 
SustentávelFailuresForBlockData
 a| 
O número previsto de falhas simultâneas que podem ocorrer sem perder a capacidade de recuperação automática para um estado de tolerância do nó para os dados.
 a| 
número inteiro



 a| 
SustentávelFailuresForMetadata
 a| 
O número previsto de falhas simultâneas que podem ocorrer sem perder a capacidade de curar automaticamente um estado de tolerância de nó para metadados.
 a| 
número inteiro

|===