---
permalink: api/reference_element_api_adddrives.html 
sidebar: sidebar 
keywords: drives,adding,cluster,drive,add,adddrives 
summary: Você pode usar o método AddDrives para adicionar uma ou mais unidades disponíveis ao cluster, permitindo que as unidades hospedem uma parte dos dados para o cluster. 
---
= AddDrives
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `AddDrives` método para adicionar uma ou mais unidades disponíveis ao cluster, permitindo que as unidades hospedem uma parte dos dados do cluster.

Quando você adiciona um nó de armazenamento ao cluster ou instala novas unidades em um nó existente, as novas unidades são marcadas como disponíveis e devem ser adicionadas via AddDrives antes que possam ser utilizadas. Use o xref:reference_element_api_listdrives.adoc[ListDrives] método para exibir as unidades que estão disponíveis para serem adicionadas. Quando você adiciona uma unidade, o sistema determina automaticamente o tipo de unidade que ela deve ser.

O método é assíncrono e retorna assim que os processos de rebalanceamento das unidades no cluster são iniciados. No entanto, pode levar mais tempo para que os dados no cluster sejam rebalanceados usando as unidades recém-adicionadas; o rebalanceamento continua mesmo após a chamada do método AddDrives estar concluída. Você pode usar o xref:reference_element_api_getasyncresult.adoc[GetAsyncResult] método para consultar o asyncHandle retornado do método. Depois que o método AddDrives retornar, você pode usar o xref:reference_element_api_listsyncjobs.adoc[ListSyncJobs] método para ver o progresso do rebalanceamento de dados com as novas unidades.


NOTE: Quando você adiciona várias unidades, é mais eficiente adicioná-las em uma única chamada de método AddDrives em vez de vários métodos individuais com uma única unidade cada. Isso reduz a quantidade de balanceamento de dados que deve ocorrer para estabilizar a carga de storage no cluster.



== Parâmetros

Este método tem os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
unidades
 a| 
Informações sobre cada unidade a ser adicionada ao cluster. Valores possíveis:

* DriveID: O ID da unidade a adicionar (inteiro).
* Tipo: O tipo de unidade a adicionar (string). Os valores válidos são "corte", "bloco" ou "volume". Se omitido, o sistema atribui o tipo correto.

 a| 
Array de objetos JSON
 a| 
Nenhum
 a| 
Sim (o tipo é opcional)

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
AsyncHandle
 a| 
Valor do manípulo utilizado para obter o resultado da operação.
 a| 
número inteiro

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "id": 1,
  "method": "AddDrives",
  "params": {
    "drives": [
      {
        "driveID": 1,
        "type": "slice"
      },
      {
        "driveID": 2,
        "type": "block"
      },
      {
        "driveID": 3,
        "type": "block"
      }
    ]
  }
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
  "id": 1,
  "result" : {
    "asyncHandle": 1
  }
}
----


== Novo desde a versão

9,6



== Encontre mais informações

* xref:reference_element_api_getasyncresult.adoc[GetAsyncResult]
* xref:reference_element_api_listdrives.adoc[ListDrives]
* xref:reference_element_api_listsyncjobs.adoc[ListSyncJobs]

