---
permalink: api/reference_element_api_listvolumesforaccount.html 
sidebar: sidebar 
keywords: volume,volumes,list,listing,account,active,pending,deleted,listvolumesforaccount 
summary: Você pode usar o método ListVolumesForAccount para listar volumes ativos e excluídos para uma conta. 
---
= ListVolumesForAccount
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ListVolumesForAccount` método para listar volumes ativos e (pendentes) excluídos de uma conta.



== Parâmetros

Este método tem os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
IncludeVirtualVolumes
 a| 
Os volumes virtuais são incluídos na resposta por padrão. Para excluir volumes virtuais, defina como false.
 a| 
booleano
 a| 
verdadeiro
 a| 
Não



 a| 
ID Contabilística
 a| 
Todos os volumes pertencentes a este AccountID são devolvidos.
 a| 
número inteiro
 a| 
Não
 a| 
Sim

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
volumes
 a| 
Lista de informações de volume.
 a| 
xref:reference_element_api_volume.adoc[volume] array

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "ListVolumesForAccount",
   "params": {
      "accountID"  : 1
   },
   "id" : 1
}
----


== Exemplo de resposta

As respostas para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
    "id": 1,
    "result": {
        "volumes": [
            {
                "access": "readWrite",
                "accountID": 1,
                "attributes": {},
                "blockSize": 4096,
                "createTime": "2018-07-22T16:15:25Z",
                "deleteTime": "",
                "enable512e": false,
                "iqn": "iqn.2010-01.com.solidfire:0oto.test1.25",
                "name": "test1",
                "purgeTime": "",
                "qos": {
                    "burstIOPS": 15000,
                    "burstTime": 60,
                    "curve": {
                        "4096": 100,
                        "8192": 160,
                        "16384": 270,
                        "32768": 500,
                        "65536": 1000,
                        "131072": 1950,
                        "262144": 3900,
                        "524288": 7600,
                        "1048576": 15000
                    },
                    "maxIOPS": 15000,
                    "minIOPS": 50
                },
                "scsiEUIDeviceID": "306f746f00000019f47acc0100000000",
                "scsiNAADeviceID": "6f47acc100000000306f746f00000019",
                "sliceCount": 1,
                "status": "active",
                "totalSize": 1000341504,
                "virtualVolumeID": null,
                "volumeAccessGroups": [],
                "volumeID": 25,
                "volumePairs": []
            }
        ]
    }
}
----


== Novo desde a versão

9,6
