---
permalink: api/reference_element_api_setremotelogginghosts.html 
sidebar: sidebar 
keywords: remote,logging,host,hosts,set,setting,setremotelogginghosts 
summary: Você pode usar o método SetRemoteLoggingHosts para configurar o log remoto dos nós no cluster de armazenamento para um servidor de log centralizado ou servidores. O registo remoto é efetuado através de TCP utilizando a porta predefinida 514. Esta API não adiciona aos hosts de log existentes. Em vez disso, ele substitui o que existe atualmente por novos valores especificados por este método API. Você pode usar GetRemoteLoggingHosts para determinar quais são os hosts de log atuais e, em seguida, usar SetRemoteLoggingHosts para definir a lista desejada de hosts de log atuais e novos. 
---
= SetRemoteLoggingHosts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `SetRemoteLoggingHosts` método para configurar o log remoto dos nós no cluster de storage para um servidor de log centralizado ou servidores. O registo remoto é efetuado através de TCP utilizando a porta predefinida 514. Esta API não adiciona aos hosts de log existentes. Em vez disso, ele substitui o que existe atualmente por novos valores especificados por este método API. Você pode usar `GetRemoteLoggingHosts` para determinar quais são os hosts de log atuais e, em seguida, usar `SetRemoteLoggingHosts` para definir a lista desejada de hosts de log atuais e novos.



== Parâmetro

Este método tem o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
RemoteHosts
 a| 
Lista de hosts que são destinatários de mensagens de log.
 a| 
xref:reference_element_api_loggingserver.adoc[Servidor de loggingServer] array
 a| 
Nenhum
 a| 
Sim

|===


== Valores de retorno

Este método não tem valores de retorno.



== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "id": 1,
   "method": "SetRemoteLoggingHosts",
   "params": {
     "remoteHosts": [
        {
          "host": "172.16.1.20",
          "port": 10514
        },
        {
          "host": "172.16.1.25"
        }
      ]
   }
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
    "id" : 1,
    "result" : {}
}
----


== Novo desde a versão

9,6



== Encontre mais informações

xref:reference_element_api_getremotelogginghosts.adoc[GetRemoteLoggingHosts]
