---
permalink: api/reference_element_api_getkeyproviderkmip.html 
sidebar: sidebar 
keywords: KMIP,key provider,retrieving,get,retrieve 
summary: 'Você pode usar o método GetKeyProviderKmip para recuperar informações sobre o provedor de chaves KMIP (Key Management Interoperability Protocol) especificado.' 
---
= GetKeyProviderKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `GetKeyProviderKmip` método para recuperar informações sobre o provedor de chaves KMIP (Key Management Interoperability Protocol) especificado.



== Parâmetros

Este método tem os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
KeyProviderID
 a| 
A ID do objeto do provedor de chaves KMIP a retornar.
 a| 
número inteiro
 a| 
Nenhum
 a| 
Sim

|===


== Valores de retorno

Este método tem os seguintes valores de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
KmipKeyProvider
 a| 
Um objeto contendo detalhes sobre o provedor de chaves solicitado.
 a| 
link:reference_element_api_keyproviderkmip.html["KeyProviderKmip"]

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "GetKeyProviderKmip",
  "params": {
    "keyProviderID": 15
    },
"id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
   "id": 1,
   "result":
    {
    "kmipKeyProvider": {
        "keyProviderID": 15,
        "kmipCapabilities": "SSL",
        "keyProviderIsActive": true,
        "keyServerIDs": [
            1
        ],
        "keyProviderName": "ProviderName"
    }
   }
}
----


== Novo desde a versão

11,7
