---
permalink: api/reference_element_api_listvolumestatsbyvirtualvolume.html 
sidebar: sidebar 
keywords: volumes,volume,virtual,stats,list,listing,listvolumestatsbyvirtualvolume,activity 
summary: Você pode usar o método ListVolumeStatsByVirtualvolume para listar estatísticas de volume para quaisquer volumes no sistema que estejam associados ao volume virtual. As estatísticas são cumulativas a partir da criação do volume. 
---
= ListVolumeStatsByVirtualvolume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ListVolumeStatsByVirtualVolume` método para listar estatísticas de volume para quaisquer volumes no sistema que estejam associados ao volume virtual. As estatísticas são cumulativas a partir da criação do volume.



== Parâmetro

Este método tem o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
VirtualVolumeIDs
 a| 
Uma lista de um ou mais IDs de volume virtuais para os quais recuperar informações. Se você especificar esse parâmetro, o método retornará informações sobre apenas esses volumes virtuais.
 a| 
Array de string UUID
 a| 
Não
 a| 
Não

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
VolumeStats
 a| 
Uma lista de objetos que contém informações de atividade para cada volume virtual no sistema.
 a| 
xref:reference_element_api_volumestats.adoc[VolumeStats] array

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "ListVolumeStatsByVirtualVolume",
  "params": {},
  "id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
  "id": 1,
  "result": {
    "volumeStats": [
      {
        "accountID": 17,
        "actualIOPS": 0,
        "asyncDelay": null,
        "averageIOPSize": 1074265444,
        "burstIOPSCredit": 0,
        "clientQueueDepth": 0,
        "desiredMetadataHosts": null,
        "latencyUSec": 0,
        "metadataHosts": {
          "deadSecondaries": [],
          "liveSecondaries": [
            26
          ],
          "primary": 56
        },
        "nonZeroBlocks": 36,
        "readBytes": 18366464,
        "readBytesLastSample": 0,
        "readLatencyUSec": 0,
        "readOps": 156,
        "readOpsLastSample": 0,
        "samplePeriodMSec": 500,
        "throttle": 0,
        "timestamp": "2016-10-10T17:46:35.914642Z",
        "unalignedReads": 156,
        "unalignedWrites": 185,
        "virtualVolumeID": "070ac0ba-f344-4f4c-b79c-142efa3642e8",
        "volumeAccessGroups": [],
        "volumeID": 12518,
        "volumeSize": 91271200768,
        "volumeUtilization": 0,
        "writeBytes": 23652213248,
        "writeBytesLastSample": 0,
        "writeLatencyUSec": 0,
        "writeOps": 185,
        "writeOpsLastSample": 0,
        "zeroBlocks": 22282972
      }
    ]
  }
}
----


== Novo desde a versão

9,6
