---
permalink: api/reference_element_api_listaccounts.html 
sidebar: sidebar 
keywords: account,accounts,list,listing,all,listaccounts 
summary: Você pode usar ListAccounts para obter toda a lista de contas de inquilinos de armazenamento, com suporte opcional de paginação. As contas Element permitem o acesso a volumes. 
---
= Contagens de listas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar `ListAccounts` para obter toda a lista de contas de inquilinos de armazenamento, com suporte opcional de paginação. As contas Element permitem o acesso a volumes.



== Parâmetros

Este método tem os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
IncludeStorageContainers
 a| 
Os contentores de armazenamento de volume virtual são incluídos na resposta por padrão. Para excluir recipientes de armazenamento, defina como false.
 a| 
booleano
 a| 
verdadeiro
 a| 
Não



 a| 
StartAccountID
 a| 
Iniciando AccountID para retornar. Se não existir uma conta com este AccountID, a próxima conta por Ordem AccountID é utilizada como o início da lista. Para percorrer a lista, passe o AccountID da última conta na resposta anterior mais 1.
 a| 
número inteiro
 a| 
Nenhum
 a| 
Não



 a| 
limite
 a| 
Número máximo de objetos de conta a serem retornados.
 a| 
número inteiro
 a| 
Nenhum
 a| 
Não

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
contas
 a| 
A lista de contas.
 a| 
xref:reference_element_api_account.adoc[conta] array

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "ListAccounts",
   "params": {
     "startAccountID"  : 0,
     "limit" : 1000
   },
   "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
   "result" : {
    "accounts": [
	{
        "attributes": {},
        "username": "jamesw",
        "targetSecret": "168#5A757ru268)",
        "volumes": [],
        "enableChap": false,
        "status": "active",
        "accountID": 16,
        "storageContainerID": "abcdef01-1234-5678-90ab-cdef01234567",
        "initiatorSecret": "168#5A757ru268)"
    },
    {
        "attributes": {},
        "username": "jimmyd",
        "targetSecret": "targetsecret",
        "volumes": [],
        "enableChap": true,
        "status": "active",
        "accountID": 5,
        "storageContainerID": "abcdef01-1234-5678-90ab-cdef01234567",
        "initiatorSecret": "initiatorsecret"
    }
  ]
}
}
----


== Novo desde a versão

9,6
