---
permalink: api/reference_element_api_listvolumestatsbyvolume.html 
sidebar: sidebar 
keywords: volumes,volume,stats,list,listing,listvolumestatsbyvolume,activity 
summary: Pode utilizar o método ListVolumeStatsByvolume para listar medições de atividade de alto nível para cada volume, por volume. Os valores são cumulativos a partir da criação do volume. 
---
= ListVolumeStatsByvolume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pode utilizar o `ListVolumeStatsByVolume` método para listar medições de atividade de alto nível para cada volume, por volume. Os valores são cumulativos a partir da criação do volume.



== Parâmetro

Este método tem o seguinte parâmetro de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
IncludeVirtualVolumes
 a| 
Os volumes virtuais são incluídos na resposta por padrão. Para excluir volumes virtuais, defina como false.
 a| 
booleano
 a| 
verdadeiro
 a| 
Não

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
VolumeStats
 a| 
Lista de informações de atividade de volume.
 a| 
xref:reference_element_api_volumestats.adoc[VolumeStats] array

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "ListVolumeStatsByVolume",
   "params": {},
   "id" : 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
  "id": 1,
  "result": {
    "volumeStats": [
        {
            "accountID": 1,
            "actualIOPS": 4,
            "asyncDelay": null,
            "averageIOPSize": 5970,
            "burstIOPSCredit": 0,
            "clientQueueDepth": 0,
            "desiredMetadataHosts": null,
            "latencyUSec": 474,
            "metadataHosts": {
                "deadSecondaries": [],
                "liveSecondaries": [
                    13
                ],
                "primary": 25
            },
            "nonZeroBlocks": 34931222,
            "normalizedIOPS": 4,
            "readBytes": 1282491003392,
            "readBytesLastSample": 0,
            "readLatencyUSec": 0,
            "readLatencyUSecTotal": 4581669750,
            "readOps": 15592933,
            "readOpsLastSample": 0,
            "samplePeriodMSec": 500,
            "sliceIopsStats": {
                "largeStatistics": {
                    "averageReadIops": 17,
                    "averageTotalIops": 43,
                    "averageWriteIops": 26,
                    "nSamples": 24,
                    "peakReadIops": 19,
                    "peakTotalIops": 47,
                    "peakWriteIops": 30,
                    "sliceID": 1
                },
                "smallStatistics": {
                    "averageReadIops": 17,
                    "averageTotalIops": 42,
                    "averageWriteIops": 25,
                    "nSamples": 120,
                    "peakReadIops": 173,
                    "peakTotalIops": 249,
                    "peakWriteIops": 77,
                    "sliceID": 1
            }
        },
        "throttle": 0,
        "timestamp": "2025-02-03T21:18:38.880100Z",
        "unalignedReads": 167319,
        "unalignedWrites": 90836,
        "volumeAccessGroups": [
            1
        ],
        "volumeID": 1,
        "volumeSize": 2147483648000,
        "volumeUtilization": 0.0002666666666666667,
        "writeBytes": 1385173585408,
        "writeBytesLastSample": 12288,
        "writeLatencyUSec": 474,
        "writeLatencyUSecTotal": 11233350905,
        "writeOps": 157060458,
        "writeOpsLastSample": 2,
        "zeroBlocks": 489356778
      }
    ]
  }
}
----


== Novo desde a versão

9,6
