---
permalink: api/reference_element_api_getnetworkconfig.html 
sidebar: sidebar 
keywords: network,config,configuration,get,getting,getnetworkconfig 
summary: Você pode usar o método GetNetworkConfig para exibir as informações de configuração de rede para um nó. 
---
= GetNetworkConfig
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `GetNetworkConfig` método para exibir as informações de configuração de rede de um nó.



[[parameters]]
== Parâmetros

Este método não tem parâmetros de entrada.



[[return-value]]
== Valor de retorno

Este método tem o seguinte valor de retorno:

|===
| Nome | Descrição | Tipo 


 a| 
rede
 a| 
Tipos de conexão de rede e configurações atuais para cada interface de rede do nó.
 a| 
xref:reference_element_api_network_all_interfaces.adoc[rede (todas as interfaces)]

|===


[[request-example]]
== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
   "method": "GetNetworkConfig",
   "params": {},
   "id" : 1
}
----


[[response-example]]
== Exemplo de resposta

Devido ao tamanho deste exemplo de resposta, ele está documentado em um tópico suplementar.



[[new-since-version]]
== Novo desde a versão

9,6



[[find-more-information]]
== Encontre mais informações

xref:reference_element_api_response_example_getnetworkconfig.adoc[GetNetworkConfig]
