---
permalink: api/reference_element_api_listvirtualvolumes.html 
sidebar: sidebar 
keywords: virtual,volume,volumes,vvol,list,listing,listvirtualvolumes 
summary: Você pode usar o método ListVirtualVolumes para listar os volumes virtuais atualmente no sistema. Você pode usar este método para listar todos os volumes virtuais ou listar apenas um subconjunto. 
---
= ListVirtualVolumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ListVirtualVolumes` método para listar os volumes virtuais atualmente no sistema. Você pode usar este método para listar todos os volumes virtuais ou listar apenas um subconjunto.



== Parâmetros

Este método tem os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
detalhes
 a| 
O nível de detalhe na resposta. Valores possíveis:

* Verdadeiro: Inclua mais detalhes sobre cada VVol na resposta.
* Falso: Inclua o nível padrão de detalhes sobre cada VVol na resposta.

 a| 
booleano
 a| 
Falso
 a| 
Não



 a| 
limite
 a| 
O número máximo de volumes virtuais a listar.
 a| 
número inteiro
 a| 
10000
 a| 
Não



 a| 
recursiva
 a| 
Especifica se devem incluir ou não informações sobre as crianças de cada VVol na resposta. Valores possíveis:

* Verdadeiro: Inclua informações sobre as crianças de cada VVol na resposta.
* Falso: Não inclua informações sobre as crianças de cada VVol na resposta.

 a| 
booleano
 a| 
Falso
 a| 
Não



 a| 
StartVirtualVolumeID
 a| 
O ID do volume virtual no qual iniciar a lista na resposta.
 a| 
UUUIDType
 a| 
Nenhum
 a| 
Não



 a| 
VirtualVolumeIDs
 a| 
Uma lista de IDs de volume virtuais para os quais recuperar informações. Se você omitir esse parâmetro, o método retornará informações sobre apenas esses volumes virtuais.
 a| 
Array UUUID virtualVolumeID
 a| 
Nenhum
 a| 
Não

|===


== Valores de retorno

Este método tem os seguintes valores de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
NextVirtualVolumeID
 a| 
A ID do próximo volume virtual na lista.
 a| 
UUID



 a| 
VirtualVolumes
 a| 
Uma lista de objetos que descrevem os volumes virtuais atualmente no sistema.
 a| 
xref:reference_element_api_virtualvolume.adoc[Virtualvolume] array

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "ListVirtualVolumes",
    "params": {
    },
    "id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
  "id": 1,
  "result": {
    "nextVirtualVolumeID": "00000000-0000-0000-0000-000000000000",
    "virtualVolumes": [
      {
        "bindings": [
          177
        ],
        "children": [],
        "metadata": {
          "SFProfileId": "f4e5bade-15a2-4805-bf8e-52318c4ce443",
          "SFgenerationId": "0",
          "VMW_ContainerId": "abaab415-bedc-44cd-98b8-f37495884db0",
          "VMW_VVolName": "asdf",
          "VMW_VVolType": "Config",
          "VMW_VmID": "502e0676-e510-ccdd-394c-667f6867fcdf",
          "VMW_VvolProfile": "f4e5bade-15a2-4805-bf8e-52318c4ce443:0"
        },
        "parentVirtualVolumeID": "00000000-0000-0000-0000-000000000000",
        "snapshotID": 0,
        "snapshotInfo": null,
        "status": "done",
        "storageContainer": {
          "accountID": 1,
          "initiatorSecret": "B5)D1y10K)8IDN58",
          "name": "test",
          "protocolEndpointType": "SCSI",
          "status": "active",
          "storageContainerID": "abaab415-bedc-44cd-98b8-f37495884db0",
          "targetSecret": "qgae@{o{~8\"2U)U^"
        },
        "virtualVolumeID": "269d3378-1ca6-4175-a18f-6d4839e5c746",
        "virtualVolumeType": "config",
        "volumeID": 166,
        "volumeInfo": null
      }
    ]
  }
}
----


== Novo desde a versão

9,6
