---
permalink: api/reference_element_api_listidpconfigurations.html 
sidebar: sidebar 
keywords: configs configurations,idp configs,list 
summary: Você pode usar o método ListIdpConfigurations para listar configurações para IDPs de terceiros. Opcionalmente, você pode fornecer o sinalizador enableOnly para recuperar a configuração IDP atualmente habilitada ou um nome UUID de metadados IDP ou IDP para consultar informações para uma configuração de IDP específica. 
---
= ListIdpConfigurations
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ListIdpConfigurations` método para listar configurações para IDPs de terceiros. Opcionalmente, você pode fornecer o `enabledOnly` sinalizador para recuperar a configuração IDP atualmente ativada ou um UUID de metadados IDP ou nome IDP para consultar informações para uma configuração IDP específica.



== Parâmetros

Este método tem os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
EnableOnly
 a| 
Filtra o resultado para retornar a configuração IDP atualmente ativada.
 a| 
booleano
 a| 
Nenhum
 a| 
Não



 a| 
IdpConfigurationID
 a| 
UUID para a configuração de IDP de terceiros.
 a| 
UUID
 a| 
Nenhum
 a| 
Não



 a| 
IdpName
 a| 
Recupera informações de configuração de IDP para um nome de IDP específico.
 a| 
cadeia de carateres
 a| 
Nenhum
 a| 
Não

|===


== Valores de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
IdpConfigInfos
 a| 
Informações sobre a(s) configuração(ões) de IDP de terceiros.
 a| 
link:reference_element_api_idpconfiginfo.html["IdpConfigInfo"] array

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "ListIdpConfigurations",
  "params": {}
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
    "result": {
        "idpConfigInfo": {
        "enabled": true,
        "idpConfigurationID": "f983c602-12f9-4c67-b214-bf505185cfed",
        "idpMetadata": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n
        <EntityDescriptor xmlns=\"urn:oasis:names:tc:SAML:2.0:metadata\"\r\n
        xmlns:ds=\"http://www.w3.org/2000/09/xmldsig#\"\r\n
        xmlns:shibmd=\"urn:mace:shibboleth:metadata:1.0\"\r\n
        xmlns:xml=\"http://www.w3.org/XML/1998/namespace\"\r\n
        ...</Organization>\r\n
        </EntityDescriptor>",
        "idpName": "https://privider.name.url.com",
        "serviceProviderCertificate": "-----BEGIN CERTIFICATE-----\n
        MI...BHi\n
        -----END CERTIFICATE-----\n",
        "spMetadataUrl": "https://10.193.100.100/auth/ui/saml2"
        }
    }
}
----


== Novo desde a versão

12,0
