---
permalink: api/reference_element_api_volumestats.html 
sidebar: sidebar 
keywords: object,objects,volumeStats 
summary: O objeto volumeStats contém dados estatísticos para um volume individual. 
---
= VolumeStats
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O objeto volumeStats contém dados estatísticos para um volume individual.



== Membros do objeto

Você pode usar os seguintes métodos para obter objetos volumeStats para alguns ou todos os volumes:

* xref:reference_element_api_getvolumestats.adoc[GetVolumeStats]
* xref:reference_element_api_listvolumestatsbyaccount.adoc[ListVolumeStatsByAccount]
* xref:reference_element_api_listvolumestatsbyvolume.adoc[ListVolumeStatsByvolume]
* xref:reference_element_api_listvolumestatsbyvolumeaccessgroup.adoc[ListVolumeStatsByVolumeAccessGroup]


Este objeto contém os seguintes membros:

|===
| Nome | Descrição | Cálculo | Tipo 


 a| 
ID Contabilística
 a| 
O ID da conta do proprietário do volume.
 a| 
N/A.
 a| 
número inteiro



 a| 
IOPS actualIOPS
 a| 
O IOPS atual do volume nos últimos 500 milissegundos.
 a| 
Ponto no tempo
 a| 
número inteiro



 a| 
AsyncDelay
 a| 
O período de tempo desde que o volume foi sincronizado pela última vez com o cluster remoto. Se o volume não estiver emparelhado, isso é nulo. *Nota:* Um volume de destino em um estado de replicação ativa sempre tem um asyncDelay de 0 (zero). Os volumes de destino são compatíveis com o sistema durante a replicação e assumem que o asyncDelay é preciso em todos os momentos.
 a| 
N/A.
 a| 
String de duração ISO 8601 ou null



 a| 
AverageIOPSize
 a| 
O tamanho médio em bytes de e/S recente para o volume nos últimos 500 milissegundos.
 a| 
Ponto no tempo
 a| 
número inteiro



 a| 
BurstIOPSCredit
 a| 
O número total de créditos IOP disponíveis para o usuário. Quando os volumes não estão usando até o maxIOPS configurado, os créditos são acumulados.
 a| 
N/A.
 a| 
número inteiro



 a| 
ClientQueueDepth
 a| 
O número de operações de leitura e gravação pendentes no volume.
 a| 
N/A.
 a| 
número inteiro



 a| 
ClusterUtilização
 a| 
A quantidade de capacidade do cluster que está sendo utilizada.
 a| 
N/A.
 a| 
flutuação



 a| 
DesiredMetadataHosts
 a| 
Os serviços de metadados (slice) a serem migrados se os metadados de volume estiverem a ser migrados entre os serviços de metadados. Um valor "nulo" significa que o volume não está migrando.
 a| 
N/A.
 a| 
Objeto JSON



 a| 
LatencyUSec
 a| 
O tempo médio, em microssegundos, para concluir as operações para o volume nos últimos 500 milissegundos. Um valor "0" (zero) significa que não há e/S para o volume.
 a| 
Ponto no tempo
 a| 
número inteiro



 a| 
MetadataHosts
 a| 
Os serviços de metadados (fatia) nos quais os metadados de volume residem. Valores possíveis:

* Primário: Os principais serviços de metadados que hospedam o volume.
* LiveSecondaries: Serviços de metadados secundários que estão atualmente em um estado "vivo".
* DeadSecondaries: Serviços de metadados secundários que estão em um estado morto.

 a| 
N/A.
 a| 
Objeto JSON



 a| 
Não ZeroBlocks
 a| 
O número total de 4KiB blocos que contêm dados após a última operação de coleta de lixo ter sido concluída.
 a| 
N/A.
 a| 
número inteiro



 a| 
ReadBytes
 a| 
O total de bytes cumulativos lidos a partir do volume desde a criação do volume.
 a| 
Monotonicamente crescente
 a| 
número inteiro



 a| 
ReadBytesLastSample
 a| 
O número total de bytes lidos do volume durante o último período de amostra.
 a| 
Ponto no tempo
 a| 
número inteiro



 a| 
ReadLatencySU
 a| 
O tempo médio, em microssegundos, para concluir as operações de leitura para o volume nos últimos 500 milissegundos.
 a| 
Ponto no tempo
 a| 
número inteiro



 a| 
ReadLatencyUSecTotal
 a| 
O tempo total gasto a realizar operações de leitura a partir do volume.
 a| 
Monotonicamente crescente
 a| 
número inteiro



 a| 
ReadOps
 a| 
O total de operações de leitura para o volume desde a criação do volume.
 a| 
Monotonicamente crescente
 a| 
número inteiro



 a| 
ReadOpsLastSample
 a| 
O número total de operações de leitura durante o último período da amostra.
 a| 
Ponto no tempo
 a| 
número inteiro



 a| 
SamplePeriodMSec
 a| 
A duração do período da amostra, em milissegundos.
 a| 
N/A.
 a| 
número inteiro



 a| 
acelerador
 a| 
Um valor flutuante entre 0 e 1 que representa o quanto o sistema está restringindo clientes abaixo de seu maxIOPS devido à re-replicação de dados, erros transitórios e snapshots obtidos.
 a| 
N/A.
 a| 
flutuação



 a| 
timestamp
 a| 
A hora atual no formato UTC-0.
 a| 
N/A.
 a| 
String de data ISO 8601



 a| 
UnalignedReads
 a| 
O total acumulado de operações de leitura desalinhadas para um volume desde a criação do volume.
 a| 
Monotonicamente crescente
 a| 
número inteiro



 a| 
UnalignedWrites
 a| 
O total de operações de gravação não alinhadas cumulativas em um volume desde a criação do volume.
 a| 
Monotonicamente crescente
 a| 
número inteiro



 a| 
Grupos de acessórios de volume
 a| 
A lista de IDs do(s) grupo(s) de acesso de volume ao qual um volume pertence.
 a| 
N/A.
 a| 
array inteiro



 a| 
VolumeID
 a| 
A ID do volume.
 a| 
N/A.
 a| 
número inteiro



 a| 
VolumeSize
 a| 
Capacidade provisionada total em bytes.
 a| 
N/A.
 a| 
número inteiro



 a| 
VolumeUtilização
 a| 
Um valor de ponto flutuante que descreve como o cliente está usando os recursos de entrada/saída do volume em comparação com a configuração de QoS maxIOPS para esse volume. Valores possíveis:

* 0: O cliente não está usando o volume.
* 0,01 a 0,99: O cliente não está utilizando totalmente os recursos de IOPS do volume.
* 1,00: O cliente está utilizando totalmente o volume até o limite de IOPS definido pela configuração maxIOPS.
* > 1,00: O cliente está utilizando mais do que o limite definido pelo maxIOPS. Isso é possível quando a configuração de QoS burstIOPS é definida mais alta do que maxIOPS. Por exemplo, se maxIOPS estiver definido como 1000 e burstIOPS estiver definido como 2000, o `volumeUtilization` valor seria 2,00 se o cliente utilizar totalmente o volume.

 a| 
N/A.
 a| 
flutuação



 a| 
Escreve Bytes
 a| 
O total de bytes cumulativos gravados no volume desde a criação do volume.
 a| 
Monotonicamente crescente
 a| 
número inteiro



 a| 
WriteBytesLastSample
 a| 
O número total de bytes gravados no volume durante o último período de amostra.
 a| 
Monotonicamente crescente
 a| 
número inteiro



 a| 
Escreva um comentário para writeLatencyUSec
 a| 
O tempo médio, em microssegundos, para concluir as operações de gravação em um volume nos últimos 500 milissegundos.
 a| 
Ponto no tempo
 a| 
número inteiro



 a| 
WriteLatencyUSecTotal
 a| 
O tempo total gasto executando operações de gravação no volume.
 a| 
Monotonicamente crescente
 a| 
número inteiro



 a| 
WriteOps
 a| 
O total de operações de gravação cumulativas no volume desde a criação do volume.
 a| 
Monotonicamente crescente
 a| 
número inteiro



 a| 
Escreva um comentário para LastSample
 a| 
O número total de operações de gravação durante o último período de amostra.
 a| 
Ponto no tempo
 a| 
número inteiro



 a| 
ZeroBlocks
 a| 
O número total de blocos vazios 4KiB sem dados após a última rodada de operação de coleta de lixo ter sido concluída.
 a| 
Ponto no tempo
 a| 
número inteiro

|===