---
permalink: api/reference_element_api_listvolumes.html 
sidebar: sidebar 
keywords: volume,volumes,list,listing,listvolumes 
summary: Você pode usar o método ListVolumes para obter uma lista de volumes que estão em um cluster. Você pode especificar os volumes que deseja retornar na lista usando os parâmetros disponíveis. 
---
= Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `ListVolumes` método para obter uma lista de volumes que estão em um cluster. Você pode especificar os volumes que deseja retornar na lista usando os parâmetros disponíveis.



== Parâmetros

Este método tem os seguintes parâmetros de entrada:

|===
| Nome | Descrição | Tipo | Valor padrão | Obrigatório 


 a| 
contas
 a| 
Somente os volumes de propriedade das contas que você especificar aqui são retornados. Mutuamente exclusivo com o parâmetro volumeIDs.
 a| 
array inteiro
 a| 
Nenhum
 a| 
Não



 a| 
IncludeVirtualVolumes
 a| 
Os volumes virtuais são incluídos na resposta por padrão. Para excluir volumes virtuais, defina como false.
 a| 
booleano
 a| 
verdadeiro
 a| 
Não



 a| 
É exibido
 a| 
Retorna volumes emparelhados ou não emparelhados. Valores possíveis:

* Verdadeiro: Retorna todos os volumes emparelhados.
* False: Retorna todos os volumes não emparelhados.

 a| 
booleano
 a| 
Nenhum
 a| 
Não



 a| 
limite
 a| 
Permite-lhe definir o número máximo de resultados de volume que são devolvidos. Mutuamente exclusivo com o parâmetro volumeIDs.
 a| 
número inteiro
 a| 
10000
 a| 
Não



 a| 
StartVolumeID
 a| 
Somente volumes com um ID maior ou igual a este valor são retornados. Mutuamente exclusivo com o parâmetro volumeIDs.
 a| 
número inteiro
 a| 
Nenhum
 a| 
Não



 a| 
VolumeIDs
 a| 
Uma lista de IDs de volume. Se você especificar esse parâmetro, outros parâmetros operarão somente neste conjunto de volumes. Mutuamente exclusivos com as contas, startVolumeID e parâmetros de limite.
 a| 
array inteiro
 a| 
Não
 a| 
Não



 a| 
Nome do volume
 a| 
Apenas as informações do objeto de volume correspondentes ao nome do volume são retornadas.
 a| 
cadeia de carateres
 a| 
Não
 a| 
Não



 a| 
VolumeStatus
 a| 
Somente volumes com status igual ao valor de status são retornados. Valores possíveis:

* a criar
* snapshotting
* ativo
* eliminado

 a| 
cadeia de carateres
 a| 
Não
 a| 
Não

|===


== Valor de retorno

Este método tem o seguinte valor de retorno:

|===


| Nome | Descrição | Tipo 


 a| 
volumes
 a| 
Lista de volumes.
 a| 
xref:reference_element_api_volume.adoc[volume] array

|===


== Exemplo de solicitação

As solicitações para este método são semelhantes ao seguinte exemplo:

[listing]
----
{
  "method": "ListVolumes",
    "params": {
        "volumeIDs": [1],
        "volumeStatus": "active",
        "isPaired": "false"
    },
    "id": 1
}
----


== Exemplo de resposta

Este método retorna uma resposta semelhante ao seguinte exemplo:

[listing]
----
{
    "id": 1,
    "result": {
        "volumes": [
            {
                "access": "readWrite",
                "accountID": 1,
                "attributes": {},
                "blockSize": 4096,
                "createTime": "2016-03-28T14:39:05Z",
                "deleteTime": "",
                "enable512e": true,
                "iqn": "iqn.2010-01.com.solidfire:testvolume1.1",
                "name": "testVolume1",
                "purgeTime": "",
                "qos": {
                    "burstIOPS": 15000,
                    "burstTime": 60,
                    "curve": {
                        "4096": 100,
                        "8192": 160,
                        "16384": 270,
                        "32768": 500,
                        "65536": 1000,
                        "131072": 1950,
                        "262144": 3900,
                        "524288": 7600,
                        "1048576": 15000
                    },
                    "maxIOPS": 15000,
                    "minIOPS": 50
                },
                "scsiEUIDeviceID": "6a79617900000001f47acc0100000000",
                "scsiNAADeviceID": "6f47acc1000000006a79617900000001",
                "sliceCount": 1,
                "status": "active",
                "totalSize": 5000658944,
                "virtualVolumeID": null,
                "volumeAccessGroups": [],
                "volumeID": 1,
                "volumePairs": []
            }
        ]
    }
}
----


== Novo desde a versão

9,6
